// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"

	store "github.com/neofyis/geopulse/internal/store"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// BulkUpsertEdges provides a mock function with given fields: ctx, edges
func (_m *MockStore) BulkUpsertEdges(ctx context.Context, edges []store.OSMEdge) error {
	ret := _m.Called(ctx, edges)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertEdges")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMEdge) error); ok {
		r0 = rf(ctx, edges)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertEdges'
type MockStore_BulkUpsertEdges_Call struct {
	*mock.Call
}

// BulkUpsertEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - edges []store.OSMEdge
func (_e *MockStore_Expecter) BulkUpsertEdges(ctx interface{}, edges interface{}) *MockStore_BulkUpsertEdges_Call {
	return &MockStore_BulkUpsertEdges_Call{Call: _e.mock.On("BulkUpsertEdges", ctx, edges)}
}

func (_c *MockStore_BulkUpsertEdges_Call) Run(run func(ctx context.Context, edges []store.OSMEdge)) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMEdge))
	})
	return _c
}

func (_c *MockStore_BulkUpsertEdges_Call) Return(_a0 error) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertEdges_Call) RunAndReturn(run func(context.Context, []store.OSMEdge) error) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsertNodes provides a mock function with given fields: ctx, nodes
func (_m *MockStore) BulkUpsertNodes(ctx context.Context, nodes []store.OSMNode) error {
	ret := _m.Called(ctx, nodes)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertNodes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMNode) error); ok {
		r0 = rf(ctx, nodes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertNodes'
type MockStore_BulkUpsertNodes_Call struct {
	*mock.Call
}

// BulkUpsertNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - nodes []store.OSMNode
func (_e *MockStore_Expecter) BulkUpsertNodes(ctx interface{}, nodes interface{}) *MockStore_BulkUpsertNodes_Call {
	return &MockStore_BulkUpsertNodes_Call{Call: _e.mock.On("BulkUpsertNodes", ctx, nodes)}
}

func (_c *MockStore_BulkUpsertNodes_Call) Run(run func(ctx context.Context, nodes []store.OSMNode)) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMNode))
	})
	return _c
}

func (_c *MockStore_BulkUpsertNodes_Call) Return(_a0 error) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertNodes_Call) RunAndReturn(run func(context.Context, []store.OSMNode) error) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsertPOIs provides a mock function with given fields: ctx, pois
func (_m *MockStore) BulkUpsertPOIs(ctx context.Context, pois []store.OSMPOI) error {
	ret := _m.Called(ctx, pois)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertPOIs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMPOI) error); ok {
		r0 = rf(ctx, pois)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertPOIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertPOIs'
type MockStore_BulkUpsertPOIs_Call struct {
	*mock.Call
}

// BulkUpsertPOIs is a helper method to define mock.On call
//   - ctx context.Context
//   - pois []store.OSMPOI
func (_e *MockStore_Expecter) BulkUpsertPOIs(ctx interface{}, pois interface{}) *MockStore_BulkUpsertPOIs_Call {
	return &MockStore_BulkUpsertPOIs_Call{Call: _e.mock.On("BulkUpsertPOIs", ctx, pois)}
}

func (_c *MockStore_BulkUpsertPOIs_Call) Run(run func(ctx context.Context, pois []store.OSMPOI)) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMPOI))
	})
	return _c
}

func (_c *MockStore_BulkUpsertPOIs_Call) Return(_a0 error) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertPOIs_Call) RunAndReturn(run func(context.Context, []store.OSMPOI) error) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Return(run)
	return _c
}

// ComputeWalkScores provides a mock function with given fields: ctx
func (_m *MockStore) ComputeWalkScores(ctx context.Context) ([]store.NodeScore, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ComputeWalkScores")
	}

	var r0 []store.NodeScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.NodeScore, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.NodeScore); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.NodeScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ComputeWalkScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeWalkScores'
type MockStore_ComputeWalkScores_Call struct {
	*mock.Call
}

// ComputeWalkScores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ComputeWalkScores(ctx interface{}) *MockStore_ComputeWalkScores_Call {
	return &MockStore_ComputeWalkScores_Call{Call: _e.mock.On("ComputeWalkScores", ctx)}
}

func (_c *MockStore_ComputeWalkScores_Call) Run(run func(ctx context.Context)) *MockStore_ComputeWalkScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ComputeWalkScores_Call) Return(_a0 []store.NodeScore, _a1 error) *MockStore_ComputeWalkScores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ComputeWalkScores_Call) RunAndReturn(run func(context.Context) ([]store.NodeScore, error)) *MockStore_ComputeWalkScores_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreatePlace(ctx context.Context, arg store.CreatePlaceParams) (store.CreatePlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlace")
	}

	var r0 store.CreatePlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.CreatePlaceParams) (store.CreatePlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.CreatePlaceParams) store.CreatePlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.CreatePlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.CreatePlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlace'
type MockStore_CreatePlace_Call struct {
	*mock.Call
}

// CreatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.CreatePlaceParams
func (_e *MockStore_Expecter) CreatePlace(ctx interface{}, arg interface{}) *MockStore_CreatePlace_Call {
	return &MockStore_CreatePlace_Call{Call: _e.mock.On("CreatePlace", ctx, arg)}
}

func (_c *MockStore_CreatePlace_Call) Run(run func(ctx context.Context, arg store.CreatePlaceParams)) *MockStore_CreatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.CreatePlaceParams))
	})
	return _c
}

func (_c *MockStore_CreatePlace_Call) Return(_a0 store.CreatePlaceRow, _a1 error) *MockStore_CreatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreatePlace_Call) RunAndReturn(run func(context.Context, store.CreatePlaceParams) (store.CreatePlaceRow, error)) *MockStore_CreatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlace provides a mock function with given fields: ctx, placeID
func (_m *MockStore) DeletePlace(ctx context.Context, placeID string) error {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeletePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlace'
type MockStore_DeletePlace_Call struct {
	*mock.Call
}

// DeletePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockStore_Expecter) DeletePlace(ctx interface{}, placeID interface{}) *MockStore_DeletePlace_Call {
	return &MockStore_DeletePlace_Call{Call: _e.mock.On("DeletePlace", ctx, placeID)}
}

func (_c *MockStore_DeletePlace_Call) Run(run func(ctx context.Context, placeID string)) *MockStore_DeletePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_DeletePlace_Call) Return(_a0 error) *MockStore_DeletePlace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeletePlace_Call) RunAndReturn(run func(context.Context, string) error) *MockStore_DeletePlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatmap provides a mock function with given fields: ctx, p
func (_m *MockStore) GetHeatmap(ctx context.Context, p store.HeatmapParams) ([]store.HeatmapRow, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatmap")
	}

	var r0 []store.HeatmapRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.HeatmapParams) ([]store.HeatmapRow, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.HeatmapParams) []store.HeatmapRow); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.HeatmapRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.HeatmapParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetHeatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatmap'
type MockStore_GetHeatmap_Call struct {
	*mock.Call
}

// GetHeatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - p store.HeatmapParams
func (_e *MockStore_Expecter) GetHeatmap(ctx interface{}, p interface{}) *MockStore_GetHeatmap_Call {
	return &MockStore_GetHeatmap_Call{Call: _e.mock.On("GetHeatmap", ctx, p)}
}

func (_c *MockStore_GetHeatmap_Call) Run(run func(ctx context.Context, p store.HeatmapParams)) *MockStore_GetHeatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.HeatmapParams))
	})
	return _c
}

func (_c *MockStore_GetHeatmap_Call) Return(_a0 []store.HeatmapRow, _a1 error) *MockStore_GetHeatmap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetHeatmap_Call) RunAndReturn(run func(context.Context, store.HeatmapParams) ([]store.HeatmapRow, error)) *MockStore_GetHeatmap_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroStops provides a mock function with given fields: ctx
func (_m *MockStore) GetMetroStops(ctx context.Context) ([]store.GetMetroStopsRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroStops")
	}

	var r0 []store.GetMetroStopsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.GetMetroStopsRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.GetMetroStopsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.GetMetroStopsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetMetroStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroStops'
type MockStore_GetMetroStops_Call struct {
	*mock.Call
}

// GetMetroStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetMetroStops(ctx interface{}) *MockStore_GetMetroStops_Call {
	return &MockStore_GetMetroStops_Call{Call: _e.mock.On("GetMetroStops", ctx)}
}

func (_c *MockStore_GetMetroStops_Call) Run(run func(ctx context.Context)) *MockStore_GetMetroStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetMetroStops_Call) Return(_a0 []store.GetMetroStopsRow, _a1 error) *MockStore_GetMetroStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetMetroStops_Call) RunAndReturn(run func(context.Context) ([]store.GetMetroStopsRow, error)) *MockStore_GetMetroStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlace provides a mock function with given fields: ctx, placeID
func (_m *MockStore) GetPlace(ctx context.Context, placeID string) (store.GetPlaceRow, error) {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlace")
	}

	var r0 store.GetPlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (store.GetPlaceRow, error)); ok {
		return rf(ctx, placeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) store.GetPlaceRow); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Get(0).(store.GetPlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlace'
type MockStore_GetPlace_Call struct {
	*mock.Call
}

// GetPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockStore_Expecter) GetPlace(ctx interface{}, placeID interface{}) *MockStore_GetPlace_Call {
	return &MockStore_GetPlace_Call{Call: _e.mock.On("GetPlace", ctx, placeID)}
}

func (_c *MockStore_GetPlace_Call) Run(run func(ctx context.Context, placeID string)) *MockStore_GetPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetPlace_Call) Return(_a0 store.GetPlaceRow, _a1 error) *MockStore_GetPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetPlace_Call) RunAndReturn(run func(context.Context, string) (store.GetPlaceRow, error)) *MockStore_GetPlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetSaturation provides a mock function with given fields: ctx, p
func (_m *MockStore) GetSaturation(ctx context.Context, p store.SaturationParams) (store.SaturationRow, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetSaturation")
	}

	var r0 store.SaturationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.SaturationParams) (store.SaturationRow, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.SaturationParams) store.SaturationRow); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(store.SaturationRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.SaturationParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetSaturation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSaturation'
type MockStore_GetSaturation_Call struct {
	*mock.Call
}

// GetSaturation is a helper method to define mock.On call
//   - ctx context.Context
//   - p store.SaturationParams
func (_e *MockStore_Expecter) GetSaturation(ctx interface{}, p interface{}) *MockStore_GetSaturation_Call {
	return &MockStore_GetSaturation_Call{Call: _e.mock.On("GetSaturation", ctx, p)}
}

func (_c *MockStore_GetSaturation_Call) Run(run func(ctx context.Context, p store.SaturationParams)) *MockStore_GetSaturation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.SaturationParams))
	})
	return _c
}

func (_c *MockStore_GetSaturation_Call) Return(_a0 store.SaturationRow, _a1 error) *MockStore_GetSaturation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetSaturation_Call) RunAndReturn(run func(context.Context, store.SaturationParams) (store.SaturationRow, error)) *MockStore_GetSaturation_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlaces provides a mock function with given fields: ctx
func (_m *MockStore) ListPlaces(ctx context.Context) ([]store.ListPlacesRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlaces")
	}

	var r0 []store.ListPlacesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ListPlacesRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ListPlacesRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlaces'
type MockStore_ListPlaces_Call struct {
	*mock.Call
}

// ListPlaces is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListPlaces(ctx interface{}) *MockStore_ListPlaces_Call {
	return &MockStore_ListPlaces_Call{Call: _e.mock.On("ListPlaces", ctx)}
}

func (_c *MockStore_ListPlaces_Call) Run(run func(ctx context.Context)) *MockStore_ListPlaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListPlaces_Call) Return(_a0 []store.ListPlacesRow, _a1 error) *MockStore_ListPlaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlaces_Call) RunAndReturn(run func(context.Context) ([]store.ListPlacesRow, error)) *MockStore_ListPlaces_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByCategory provides a mock function with given fields: ctx, category
func (_m *MockStore) ListPlacesByCategory(ctx context.Context, category pgtype.Text) ([]store.ListPlacesByCategoryRow, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByCategory")
	}

	var r0 []store.ListPlacesByCategoryRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) ([]store.ListPlacesByCategoryRow, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) []store.ListPlacesByCategoryRow); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByCategoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Text) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByCategory'
type MockStore_ListPlacesByCategory_Call struct {
	*mock.Call
}

// ListPlacesByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category pgtype.Text
func (_e *MockStore_Expecter) ListPlacesByCategory(ctx interface{}, category interface{}) *MockStore_ListPlacesByCategory_Call {
	return &MockStore_ListPlacesByCategory_Call{Call: _e.mock.On("ListPlacesByCategory", ctx, category)}
}

func (_c *MockStore_ListPlacesByCategory_Call) Run(run func(ctx context.Context, category pgtype.Text)) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.Text))
	})
	return _c
}

func (_c *MockStore_ListPlacesByCategory_Call) Return(_a0 []store.ListPlacesByCategoryRow, _a1 error) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByCategory_Call) RunAndReturn(run func(context.Context, pgtype.Text) ([]store.ListPlacesByCategoryRow, error)) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByCategoryAndTag provides a mock function with given fields: ctx, arg
func (_m *MockStore) ListPlacesByCategoryAndTag(ctx context.Context, arg store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByCategoryAndTag")
	}

	var r0 []store.ListPlacesByCategoryAndTagRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.ListPlacesByCategoryAndTagParams) []store.ListPlacesByCategoryAndTagRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByCategoryAndTagRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.ListPlacesByCategoryAndTagParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByCategoryAndTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByCategoryAndTag'
type MockStore_ListPlacesByCategoryAndTag_Call struct {
	*mock.Call
}

// ListPlacesByCategoryAndTag is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.ListPlacesByCategoryAndTagParams
func (_e *MockStore_Expecter) ListPlacesByCategoryAndTag(ctx interface{}, arg interface{}) *MockStore_ListPlacesByCategoryAndTag_Call {
	return &MockStore_ListPlacesByCategoryAndTag_Call{Call: _e.mock.On("ListPlacesByCategoryAndTag", ctx, arg)}
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) Run(run func(ctx context.Context, arg store.ListPlacesByCategoryAndTagParams)) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.ListPlacesByCategoryAndTagParams))
	})
	return _c
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) Return(_a0 []store.ListPlacesByCategoryAndTagRow, _a1 error) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) RunAndReturn(run func(context.Context, store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error)) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByTag provides a mock function with given fields: ctx, dollar_1
func (_m *MockStore) ListPlacesByTag(ctx context.Context, dollar_1 string) ([]store.ListPlacesByTagRow, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByTag")
	}

	var r0 []store.ListPlacesByTagRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.ListPlacesByTagRow, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.ListPlacesByTagRow); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByTagRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByTag'
type MockStore_ListPlacesByTag_Call struct {
	*mock.Call
}

// ListPlacesByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 string
func (_e *MockStore_Expecter) ListPlacesByTag(ctx interface{}, dollar_1 interface{}) *MockStore_ListPlacesByTag_Call {
	return &MockStore_ListPlacesByTag_Call{Call: _e.mock.On("ListPlacesByTag", ctx, dollar_1)}
}

func (_c *MockStore_ListPlacesByTag_Call) Run(run func(ctx context.Context, dollar_1 string)) *MockStore_ListPlacesByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_ListPlacesByTag_Call) Return(_a0 []store.ListPlacesByTagRow, _a1 error) *MockStore_ListPlacesByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByTag_Call) RunAndReturn(run func(context.Context, string) ([]store.ListPlacesByTagRow, error)) *MockStore_ListPlacesByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesNeedingEnrichment provides a mock function with given fields: ctx
func (_m *MockStore) ListPlacesNeedingEnrichment(ctx context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesNeedingEnrichment")
	}

	var r0 []store.ListPlacesNeedingEnrichmentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ListPlacesNeedingEnrichmentRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesNeedingEnrichmentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesNeedingEnrichment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesNeedingEnrichment'
type MockStore_ListPlacesNeedingEnrichment_Call struct {
	*mock.Call
}

// ListPlacesNeedingEnrichment is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListPlacesNeedingEnrichment(ctx interface{}) *MockStore_ListPlacesNeedingEnrichment_Call {
	return &MockStore_ListPlacesNeedingEnrichment_Call{Call: _e.mock.On("ListPlacesNeedingEnrichment", ctx)}
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) Run(run func(ctx context.Context)) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) Return(_a0 []store.ListPlacesNeedingEnrichmentRow, _a1 error) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) RunAndReturn(run func(context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error)) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Return(run)
	return _c
}

// PropagateEdgeScores provides a mock function with given fields: ctx
func (_m *MockStore) PropagateEdgeScores(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PropagateEdgeScores")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_PropagateEdgeScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PropagateEdgeScores'
type MockStore_PropagateEdgeScores_Call struct {
	*mock.Call
}

// PropagateEdgeScores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) PropagateEdgeScores(ctx interface{}) *MockStore_PropagateEdgeScores_Call {
	return &MockStore_PropagateEdgeScores_Call{Call: _e.mock.On("PropagateEdgeScores", ctx)}
}

func (_c *MockStore_PropagateEdgeScores_Call) Run(run func(ctx context.Context)) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_PropagateEdgeScores_Call) Return(_a0 error) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_PropagateEdgeScores_Call) RunAndReturn(run func(context.Context) error) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNodeWalkScores provides a mock function with given fields: ctx, scores
func (_m *MockStore) UpdateNodeWalkScores(ctx context.Context, scores []store.NodeScore) error {
	ret := _m.Called(ctx, scores)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeWalkScores")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.NodeScore) error); ok {
		r0 = rf(ctx, scores)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdateNodeWalkScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNodeWalkScores'
type MockStore_UpdateNodeWalkScores_Call struct {
	*mock.Call
}

// UpdateNodeWalkScores is a helper method to define mock.On call
//   - ctx context.Context
//   - scores []store.NodeScore
func (_e *MockStore_Expecter) UpdateNodeWalkScores(ctx interface{}, scores interface{}) *MockStore_UpdateNodeWalkScores_Call {
	return &MockStore_UpdateNodeWalkScores_Call{Call: _e.mock.On("UpdateNodeWalkScores", ctx, scores)}
}

func (_c *MockStore_UpdateNodeWalkScores_Call) Run(run func(ctx context.Context, scores []store.NodeScore)) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.NodeScore))
	})
	return _c
}

func (_c *MockStore_UpdateNodeWalkScores_Call) Return(_a0 error) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdateNodeWalkScores_Call) RunAndReturn(run func(context.Context, []store.NodeScore) error) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdatePlace(ctx context.Context, arg store.UpdatePlaceParams) (store.UpdatePlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlace")
	}

	var r0 store.UpdatePlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceParams) (store.UpdatePlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceParams) store.UpdatePlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.UpdatePlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UpdatePlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlace'
type MockStore_UpdatePlace_Call struct {
	*mock.Call
}

// UpdatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdatePlaceParams
func (_e *MockStore_Expecter) UpdatePlace(ctx interface{}, arg interface{}) *MockStore_UpdatePlace_Call {
	return &MockStore_UpdatePlace_Call{Call: _e.mock.On("UpdatePlace", ctx, arg)}
}

func (_c *MockStore_UpdatePlace_Call) Run(run func(ctx context.Context, arg store.UpdatePlaceParams)) *MockStore_UpdatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpdatePlaceParams))
	})
	return _c
}

func (_c *MockStore_UpdatePlace_Call) Return(_a0 store.UpdatePlaceRow, _a1 error) *MockStore_UpdatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdatePlace_Call) RunAndReturn(run func(context.Context, store.UpdatePlaceParams) (store.UpdatePlaceRow, error)) *MockStore_UpdatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlaceEnrichment provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdatePlaceEnrichment(ctx context.Context, arg store.UpdatePlaceEnrichmentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlaceEnrichment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceEnrichmentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdatePlaceEnrichment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlaceEnrichment'
type MockStore_UpdatePlaceEnrichment_Call struct {
	*mock.Call
}

// UpdatePlaceEnrichment is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdatePlaceEnrichmentParams
func (_e *MockStore_Expecter) UpdatePlaceEnrichment(ctx interface{}, arg interface{}) *MockStore_UpdatePlaceEnrichment_Call {
	return &MockStore_UpdatePlaceEnrichment_Call{Call: _e.mock.On("UpdatePlaceEnrichment", ctx, arg)}
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) Run(run func(ctx context.Context, arg store.UpdatePlaceEnrichmentParams)) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpdatePlaceEnrichmentParams))
	})
	return _c
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) Return(_a0 error) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) RunAndReturn(run func(context.Context, store.UpdatePlaceEnrichmentParams) error) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpsertPlace(ctx context.Context, arg store.UpsertPlaceParams) (store.UpsertPlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPlace")
	}

	var r0 store.UpsertPlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpsertPlaceParams) (store.UpsertPlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UpsertPlaceParams) store.UpsertPlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.UpsertPlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UpsertPlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpsertPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPlace'
type MockStore_UpsertPlace_Call struct {
	*mock.Call
}

// UpsertPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpsertPlaceParams
func (_e *MockStore_Expecter) UpsertPlace(ctx interface{}, arg interface{}) *MockStore_UpsertPlace_Call {
	return &MockStore_UpsertPlace_Call{Call: _e.mock.On("UpsertPlace", ctx, arg)}
}

func (_c *MockStore_UpsertPlace_Call) Run(run func(ctx context.Context, arg store.UpsertPlaceParams)) *MockStore_UpsertPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpsertPlaceParams))
	})
	return _c
}

func (_c *MockStore_UpsertPlace_Call) Return(_a0 store.UpsertPlaceRow, _a1 error) *MockStore_UpsertPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpsertPlace_Call) RunAndReturn(run func(context.Context, store.UpsertPlaceParams) (store.UpsertPlaceRow, error)) *MockStore_UpsertPlace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
