// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	app "github.com/neofyis/geopulse/internal/app"
	generated "github.com/neofyis/geopulse/internal/generated"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreatePlace provides a mock function with given fields: ctx, req
func (_m *MockService) CreatePlace(ctx context.Context, req generated.CreatePlaceRequest) (*generated.Place, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreatePlaceRequest) (*generated.Place, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreatePlaceRequest) *generated.Place); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, generated.CreatePlaceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlace'
type MockService_CreatePlace_Call struct {
	*mock.Call
}

// CreatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - req generated.CreatePlaceRequest
func (_e *MockService_Expecter) CreatePlace(ctx interface{}, req interface{}) *MockService_CreatePlace_Call {
	return &MockService_CreatePlace_Call{Call: _e.mock.On("CreatePlace", ctx, req)}
}

func (_c *MockService_CreatePlace_Call) Run(run func(ctx context.Context, req generated.CreatePlaceRequest)) *MockService_CreatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(generated.CreatePlaceRequest))
	})
	return _c
}

func (_c *MockService_CreatePlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_CreatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreatePlace_Call) RunAndReturn(run func(context.Context, generated.CreatePlaceRequest) (*generated.Place, error)) *MockService_CreatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRetailListing provides a mock function with given fields: ctx, req
func (_m *MockService) CreateRetailListing(ctx context.Context, req generated.CreateRetailListingRequest) (*generated.RetailListing, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRetailListing")
	}

	var r0 *generated.RetailListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreateRetailListingRequest) (*generated.RetailListing, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreateRetailListingRequest) *generated.RetailListing); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.RetailListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, generated.CreateRetailListingRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRetailListing'
type MockService_CreateRetailListing_Call struct {
	*mock.Call
}

// CreateRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - req generated.CreateRetailListingRequest
func (_e *MockService_Expecter) CreateRetailListing(ctx interface{}, req interface{}) *MockService_CreateRetailListing_Call {
	return &MockService_CreateRetailListing_Call{Call: _e.mock.On("CreateRetailListing", ctx, req)}
}

func (_c *MockService_CreateRetailListing_Call) Run(run func(ctx context.Context, req generated.CreateRetailListingRequest)) *MockService_CreateRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(generated.CreateRetailListingRequest))
	})
	return _c
}

func (_c *MockService_CreateRetailListing_Call) Return(_a0 *generated.RetailListing, _a1 error) *MockService_CreateRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateRetailListing_Call) RunAndReturn(run func(context.Context, generated.CreateRetailListingRequest) (*generated.RetailListing, error)) *MockService_CreateRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlace provides a mock function with given fields: ctx, placeID
func (_m *MockService) DeletePlace(ctx context.Context, placeID string) error {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeletePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlace'
type MockService_DeletePlace_Call struct {
	*mock.Call
}

// DeletePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockService_Expecter) DeletePlace(ctx interface{}, placeID interface{}) *MockService_DeletePlace_Call {
	return &MockService_DeletePlace_Call{Call: _e.mock.On("DeletePlace", ctx, placeID)}
}

func (_c *MockService_DeletePlace_Call) Run(run func(ctx context.Context, placeID string)) *MockService_DeletePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeletePlace_Call) Return(_a0 error) *MockService_DeletePlace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeletePlace_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeletePlace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRetailListing provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteRetailListing(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRetailListing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRetailListing'
type MockService_DeleteRetailListing_Call struct {
	*mock.Call
}

// DeleteRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteRetailListing(ctx interface{}, id interface{}) *MockService_DeleteRetailListing_Call {
	return &MockService_DeleteRetailListing_Call{Call: _e.mock.On("DeleteRetailListing", ctx, id)}
}

func (_c *MockService_DeleteRetailListing_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteRetailListing_Call) Return(_a0 error) *MockService_DeleteRetailListing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteRetailListing_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// ExportCSV provides a mock function with given fields: ctx, w, simple
func (_m *MockService) ExportCSV(ctx context.Context, w io.Writer, simple bool) error {
	ret := _m.Called(ctx, w, simple)

	if len(ret) == 0 {
		panic("no return value specified for ExportCSV")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Writer, bool) error); ok {
		r0 = rf(ctx, w, simple)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ExportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCSV'
type MockService_ExportCSV_Call struct {
	*mock.Call
}

// ExportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - w io.Writer
//   - simple bool
func (_e *MockService_Expecter) ExportCSV(ctx interface{}, w interface{}, simple interface{}) *MockService_ExportCSV_Call {
	return &MockService_ExportCSV_Call{Call: _e.mock.On("ExportCSV", ctx, w, simple)}
}

func (_c *MockService_ExportCSV_Call) Run(run func(ctx context.Context, w io.Writer, simple bool)) *MockService_ExportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Writer), args[2].(bool))
	})
	return _c
}

func (_c *MockService_ExportCSV_Call) Return(_a0 error) *MockService_ExportCSV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ExportCSV_Call) RunAndReturn(run func(context.Context, io.Writer, bool) error) *MockService_ExportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatmap provides a mock function with given fields: ctx, minLat, minLng, maxLat, maxLng, cellSize, category
func (_m *MockService) GetHeatmap(ctx context.Context, minLat float64, minLng float64, maxLat float64, maxLng float64, cellSize float64, category string) ([]generated.HeatmapTile, error) {
	ret := _m.Called(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatmap")
	}

	var r0 []generated.HeatmapTile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, float64, string) ([]generated.HeatmapTile, error)); ok {
		return rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, float64, string) []generated.HeatmapTile); ok {
		r0 = rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]generated.HeatmapTile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, float64, float64, string) error); ok {
		r1 = rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetHeatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatmap'
type MockService_GetHeatmap_Call struct {
	*mock.Call
}

// GetHeatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - minLat float64
//   - minLng float64
//   - maxLat float64
//   - maxLng float64
//   - cellSize float64
//   - category string
func (_e *MockService_Expecter) GetHeatmap(ctx interface{}, minLat interface{}, minLng interface{}, maxLat interface{}, maxLng interface{}, cellSize interface{}, category interface{}) *MockService_GetHeatmap_Call {
	return &MockService_GetHeatmap_Call{Call: _e.mock.On("GetHeatmap", ctx, minLat, minLng, maxLat, maxLng, cellSize, category)}
}

func (_c *MockService_GetHeatmap_Call) Run(run func(ctx context.Context, minLat float64, minLng float64, maxLat float64, maxLng float64, cellSize float64, category string)) *MockService_GetHeatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(float64), args[5].(float64), args[6].(string))
	})
	return _c
}

func (_c *MockService_GetHeatmap_Call) Return(_a0 []generated.HeatmapTile, _a1 error) *MockService_GetHeatmap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetHeatmap_Call) RunAndReturn(run func(context.Context, float64, float64, float64, float64, float64, string) ([]generated.HeatmapTile, error)) *MockService_GetHeatmap_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroShapes provides a mock function with given fields: ctx
func (_m *MockService) GetMetroShapes(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroShapes")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetroShapes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroShapes'
type MockService_GetMetroShapes_Call struct {
	*mock.Call
}

// GetMetroShapes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMetroShapes(ctx interface{}) *MockService_GetMetroShapes_Call {
	return &MockService_GetMetroShapes_Call{Call: _e.mock.On("GetMetroShapes", ctx)}
}

func (_c *MockService_GetMetroShapes_Call) Run(run func(ctx context.Context)) *MockService_GetMetroShapes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMetroShapes_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetMetroShapes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetroShapes_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetMetroShapes_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroStops provides a mock function with given fields: ctx
func (_m *MockService) GetMetroStops(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroStops")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetroStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroStops'
type MockService_GetMetroStops_Call struct {
	*mock.Call
}

// GetMetroStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMetroStops(ctx interface{}) *MockService_GetMetroStops_Call {
	return &MockService_GetMetroStops_Call{Call: _e.mock.On("GetMetroStops", ctx)}
}

func (_c *MockService_GetMetroStops_Call) Run(run func(ctx context.Context)) *MockService_GetMetroStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMetroStops_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetMetroStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetroStops_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetMetroStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitStops provides a mock function with given fields: ctx
func (_m *MockService) GetTransitStops(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitStops")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetTransitStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitStops'
type MockService_GetTransitStops_Call struct {
	*mock.Call
}

// GetTransitStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetTransitStops(ctx interface{}) *MockService_GetTransitStops_Call {
	return &MockService_GetTransitStops_Call{Call: _e.mock.On("GetTransitStops", ctx)}
}

func (_c *MockService_GetTransitStops_Call) Run(run func(ctx context.Context)) *MockService_GetTransitStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetTransitStops_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetTransitStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetTransitStops_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetTransitStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetParkingZones provides a mock function with given fields: ctx
func (_m *MockService) GetParkingZones(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetParkingZones")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetParkingZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParkingZones'
type MockService_GetParkingZones_Call struct {
	*mock.Call
}

// GetParkingZones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetParkingZones(ctx interface{}) *MockService_GetParkingZones_Call {
	return &MockService_GetParkingZones_Call{Call: _e.mock.On("GetParkingZones", ctx)}
}

func (_c *MockService_GetParkingZones_Call) Run(run func(ctx context.Context)) *MockService_GetParkingZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetParkingZones_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetParkingZones_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetParkingZones_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetParkingZones_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlace provides a mock function with given fields: ctx, placeID
func (_m *MockService) GetPlace(ctx context.Context, placeID string) (*generated.Place, error) {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*generated.Place, error)); ok {
		return rf(ctx, placeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *generated.Place); ok {
		r0 = rf(ctx, placeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlace'
type MockService_GetPlace_Call struct {
	*mock.Call
}

// GetPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockService_Expecter) GetPlace(ctx interface{}, placeID interface{}) *MockService_GetPlace_Call {
	return &MockService_GetPlace_Call{Call: _e.mock.On("GetPlace", ctx, placeID)}
}

func (_c *MockService_GetPlace_Call) Run(run func(ctx context.Context, placeID string)) *MockService_GetPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetPlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_GetPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetPlace_Call) RunAndReturn(run func(context.Context, string) (*generated.Place, error)) *MockService_GetPlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetailListing provides a mock function with given fields: ctx, id
func (_m *MockService) GetRetailListing(ctx context.Context, id string) (*generated.RetailListing, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRetailListing")
	}

	var r0 *generated.RetailListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*generated.RetailListing, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *generated.RetailListing); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.RetailListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetailListing'
type MockService_GetRetailListing_Call struct {
	*mock.Call
}

// GetRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetRetailListing(ctx interface{}, id interface{}) *MockService_GetRetailListing_Call {
	return &MockService_GetRetailListing_Call{Call: _e.mock.On("GetRetailListing", ctx, id)}
}

func (_c *MockService_GetRetailListing_Call) Run(run func(ctx context.Context, id string)) *MockService_GetRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetRetailListing_Call) Return(_a0 *generated.RetailListing, _a1 error) *MockService_GetRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetRetailListing_Call) RunAndReturn(run func(context.Context, string) (*generated.RetailListing, error)) *MockService_GetRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// GetSaturation provides a mock function with given fields: ctx, lat, lng, radius, category
func (_m *MockService) GetSaturation(ctx context.Context, lat float64, lng float64, radius float64, category string) (*generated.SaturationResult, error) {
	ret := _m.Called(ctx, lat, lng, radius, category)

	if len(ret) == 0 {
		panic("no return value specified for GetSaturation")
	}

	var r0 *generated.SaturationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, string) (*generated.SaturationResult, error)); ok {
		return rf(ctx, lat, lng, radius, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, string) *generated.SaturationResult); ok {
		r0 = rf(ctx, lat, lng, radius, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.SaturationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, string) error); ok {
		r1 = rf(ctx, lat, lng, radius, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetSaturation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSaturation'
type MockService_GetSaturation_Call struct {
	*mock.Call
}

// GetSaturation is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
//   - radius float64
//   - category string
func (_e *MockService_Expecter) GetSaturation(ctx interface{}, lat interface{}, lng interface{}, radius interface{}, category interface{}) *MockService_GetSaturation_Call {
	return &MockService_GetSaturation_Call{Call: _e.mock.On("GetSaturation", ctx, lat, lng, radius, category)}
}

func (_c *MockService_GetSaturation_Call) Run(run func(ctx context.Context, lat float64, lng float64, radius float64, category string)) *MockService_GetSaturation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(string))
	})
	return _c
}

func (_c *MockService_GetSaturation_Call) Return(_a0 *generated.SaturationResult, _a1 error) *MockService_GetSaturation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetSaturation_Call) RunAndReturn(run func(context.Context, float64, float64, float64, string) (*generated.SaturationResult, error)) *MockService_GetSaturation_Call {
	_c.Call.Return(run)
	return _c
}

// GetSofiaplanContext provides a mock function with given fields: ctx, lat, lng
func (_m *MockService) GetSofiaplanContext(ctx context.Context, lat float64, lng float64) (*generated.LocationContext, error) {
	ret := _m.Called(ctx, lat, lng)

	if len(ret) == 0 {
		panic("no return value specified for GetSofiaplanContext")
	}

	var r0 *generated.LocationContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (*generated.LocationContext, error)); ok {
		return rf(ctx, lat, lng)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) *generated.LocationContext); ok {
		r0 = rf(ctx, lat, lng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.LocationContext)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lat, lng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetSofiaplanContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSofiaplanContext'
type MockService_GetSofiaplanContext_Call struct {
	*mock.Call
}

// GetSofiaplanContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
func (_e *MockService_Expecter) GetSofiaplanContext(ctx interface{}, lat interface{}, lng interface{}) *MockService_GetSofiaplanContext_Call {
	return &MockService_GetSofiaplanContext_Call{Call: _e.mock.On("GetSofiaplanContext", ctx, lat, lng)}
}

func (_c *MockService_GetSofiaplanContext_Call) Run(run func(ctx context.Context, lat float64, lng float64)) *MockService_GetSofiaplanContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockService_GetSofiaplanContext_Call) Return(_a0 *generated.LocationContext, _a1 error) *MockService_GetSofiaplanContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetSofiaplanContext_Call) RunAndReturn(run func(context.Context, float64, float64) (*generated.LocationContext, error)) *MockService_GetSofiaplanContext_Call {
	_c.Call.Return(run)
	return _c
}

// ImportCSV provides a mock function with given fields: ctx, r
func (_m *MockService) ImportCSV(ctx context.Context, r io.Reader) (int, error) {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for ImportCSV")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) (int, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) int); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ImportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportCSV'
type MockService_ImportCSV_Call struct {
	*mock.Call
}

// ImportCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - r io.Reader
func (_e *MockService_Expecter) ImportCSV(ctx interface{}, r interface{}) *MockService_ImportCSV_Call {
	return &MockService_ImportCSV_Call{Call: _e.mock.On("ImportCSV", ctx, r)}
}

func (_c *MockService_ImportCSV_Call) Run(run func(ctx context.Context, r io.Reader)) *MockService_ImportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockService_ImportCSV_Call) Return(_a0 int, _a1 error) *MockService_ImportCSV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ImportCSV_Call) RunAndReturn(run func(context.Context, io.Reader) (int, error)) *MockService_ImportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// ImportOSMNetwork provides a mock function with given fields: ctx
func (_m *MockService) ImportOSMNetwork(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ImportOSMNetwork")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ImportOSMNetwork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportOSMNetwork'
type MockService_ImportOSMNetwork_Call struct {
	*mock.Call
}

// ImportOSMNetwork is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ImportOSMNetwork(ctx interface{}) *MockService_ImportOSMNetwork_Call {
	return &MockService_ImportOSMNetwork_Call{Call: _e.mock.On("ImportOSMNetwork", ctx)}
}

func (_c *MockService_ImportOSMNetwork_Call) Run(run func(ctx context.Context)) *MockService_ImportOSMNetwork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ImportOSMNetwork_Call) Return(_a0 error) *MockService_ImportOSMNetwork_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ImportOSMNetwork_Call) RunAndReturn(run func(context.Context) error) *MockService_ImportOSMNetwork_Call {
	_c.Call.Return(run)
	return _c
}

// ImportOSMPOIs provides a mock function with given fields: ctx
func (_m *MockService) ImportOSMPOIs(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ImportOSMPOIs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ImportOSMPOIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportOSMPOIs'
type MockService_ImportOSMPOIs_Call struct {
	*mock.Call
}

// ImportOSMPOIs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ImportOSMPOIs(ctx interface{}) *MockService_ImportOSMPOIs_Call {
	return &MockService_ImportOSMPOIs_Call{Call: _e.mock.On("ImportOSMPOIs", ctx)}
}

func (_c *MockService_ImportOSMPOIs_Call) Run(run func(ctx context.Context)) *MockService_ImportOSMPOIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ImportOSMPOIs_Call) Return(_a0 error) *MockService_ImportOSMPOIs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ImportOSMPOIs_Call) RunAndReturn(run func(context.Context) error) *MockService_ImportOSMPOIs_Call {
	_c.Call.Return(run)
	return _c
}

// ImportSofiaplan provides a mock function with given fields: ctx, layer
func (_m *MockService) ImportSofiaplan(ctx context.Context, layer string) error {
	ret := _m.Called(ctx, layer)

	if len(ret) == 0 {
		panic("no return value specified for ImportSofiaplan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, layer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ImportSofiaplan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportSofiaplan'
type MockService_ImportSofiaplan_Call struct {
	*mock.Call
}

// ImportSofiaplan is a helper method to define mock.On call
//   - ctx context.Context
//   - layer string
func (_e *MockService_Expecter) ImportSofiaplan(ctx interface{}, layer interface{}) *MockService_ImportSofiaplan_Call {
	return &MockService_ImportSofiaplan_Call{Call: _e.mock.On("ImportSofiaplan", ctx, layer)}
}

func (_c *MockService_ImportSofiaplan_Call) Run(run func(ctx context.Context, layer string)) *MockService_ImportSofiaplan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_ImportSofiaplan_Call) Return(_a0 error) *MockService_ImportSofiaplan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ImportSofiaplan_Call) RunAndReturn(run func(context.Context, string) error) *MockService_ImportSofiaplan_Call {
	_c.Call.Return(run)
	return _c
}

// ListNeighborhoods provides a mock function with given fields: ctx
func (_m *MockService) ListNeighborhoods(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNeighborhoods")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListNeighborhoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNeighborhoods'
type MockService_ListNeighborhoods_Call struct {
	*mock.Call
}

// ListNeighborhoods is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListNeighborhoods(ctx interface{}) *MockService_ListNeighborhoods_Call {
	return &MockService_ListNeighborhoods_Call{Call: _e.mock.On("ListNeighborhoods", ctx)}
}

func (_c *MockService_ListNeighborhoods_Call) Run(run func(ctx context.Context)) *MockService_ListNeighborhoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListNeighborhoods_Call) Return(_a0 []string, _a1 error) *MockService_ListNeighborhoods_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListNeighborhoods_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockService_ListNeighborhoods_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlaces provides a mock function with given fields: ctx, category, tag
func (_m *MockService) ListPlaces(ctx context.Context, category string, tag string) ([]generated.Place, error) {
	ret := _m.Called(ctx, category, tag)

	if len(ret) == 0 {
		panic("no return value specified for ListPlaces")
	}

	var r0 []generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]generated.Place, error)); ok {
		return rf(ctx, category, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []generated.Place); ok {
		r0 = rf(ctx, category, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, category, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListPlaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlaces'
type MockService_ListPlaces_Call struct {
	*mock.Call
}

// ListPlaces is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
//   - tag string
func (_e *MockService_Expecter) ListPlaces(ctx interface{}, category interface{}, tag interface{}) *MockService_ListPlaces_Call {
	return &MockService_ListPlaces_Call{Call: _e.mock.On("ListPlaces", ctx, category, tag)}
}

func (_c *MockService_ListPlaces_Call) Run(run func(ctx context.Context, category string, tag string)) *MockService_ListPlaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_ListPlaces_Call) Return(_a0 []generated.Place, _a1 error) *MockService_ListPlaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListPlaces_Call) RunAndReturn(run func(context.Context, string, string) ([]generated.Place, error)) *MockService_ListPlaces_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdresLocations provides a mock function with given fields: ctx
func (_m *MockService) ListAdresLocations(ctx context.Context) ([]app.AdresLocation, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAdresLocations")
	}

	var r0 []app.AdresLocation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]app.AdresLocation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []app.AdresLocation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.AdresLocation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListAdresLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdresLocations'
type MockService_ListAdresLocations_Call struct {
	*mock.Call
}

// ListAdresLocations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListAdresLocations(ctx interface{}) *MockService_ListAdresLocations_Call {
	return &MockService_ListAdresLocations_Call{Call: _e.mock.On("ListAdresLocations", ctx)}
}

func (_c *MockService_ListAdresLocations_Call) Run(run func(ctx context.Context)) *MockService_ListAdresLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListAdresLocations_Call) Return(_a0 []app.AdresLocation, _a1 error) *MockService_ListAdresLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListAdresLocations_Call) RunAndReturn(run func(context.Context) ([]app.AdresLocation, error)) *MockService_ListAdresLocations_Call {
	_c.Call.Return(run)
	return _c
}

// ListRetailListings provides a mock function with given fields: ctx
func (_m *MockService) ListRetailListings(ctx context.Context) ([]generated.RetailListing, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRetailListings")
	}

	var r0 []generated.RetailListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]generated.RetailListing, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []generated.RetailListing); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]generated.RetailListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListRetailListings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRetailListings'
type MockService_ListRetailListings_Call struct {
	*mock.Call
}

// ListRetailListings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListRetailListings(ctx interface{}) *MockService_ListRetailListings_Call {
	return &MockService_ListRetailListings_Call{Call: _e.mock.On("ListRetailListings", ctx)}
}

func (_c *MockService_ListRetailListings_Call) Run(run func(ctx context.Context)) *MockService_ListRetailListings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_ListRetailListings_Call) Return(_a0 []generated.RetailListing, _a1 error) *MockService_ListRetailListings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListRetailListings_Call) RunAndReturn(run func(context.Context) ([]generated.RetailListing, error)) *MockService_ListRetailListings_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with given fields: ctx
func (_m *MockService) Ready(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Ready(ctx interface{}) *MockService_Ready_Call {
	return &MockService_Ready_Call{Call: _e.mock.On("Ready", ctx)}
}

func (_c *MockService_Ready_Call) Run(run func(ctx context.Context)) *MockService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Ready_Call) Return(_a0 error) *MockService_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Ready_Call) RunAndReturn(run func(context.Context) error) *MockService_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// StartEnricher provides a mock function with given fields: ctx
func (_m *MockService) StartEnricher(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartEnricher")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_StartEnricher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEnricher'
type MockService_StartEnricher_Call struct {
	*mock.Call
}

// StartEnricher is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) StartEnricher(ctx interface{}) *MockService_StartEnricher_Call {
	return &MockService_StartEnricher_Call{Call: _e.mock.On("StartEnricher", ctx)}
}

func (_c *MockService_StartEnricher_Call) Run(run func(ctx context.Context)) *MockService_StartEnricher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_StartEnricher_Call) Return(_a0 error) *MockService_StartEnricher_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_StartEnricher_Call) RunAndReturn(run func(context.Context) error) *MockService_StartEnricher_Call {
	_c.Call.Return(run)
	return _c
}

// StartScraper provides a mock function with given fields: ctx
func (_m *MockService) StartScraper(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartScraper")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_StartScraper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartScraper'
type MockService_StartScraper_Call struct {
	*mock.Call
}

// StartScraper is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) StartScraper(ctx interface{}) *MockService_StartScraper_Call {
	return &MockService_StartScraper_Call{Call: _e.mock.On("StartScraper", ctx)}
}

func (_c *MockService_StartScraper_Call) Run(run func(ctx context.Context)) *MockService_StartScraper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_StartScraper_Call) Return(_a0 error) *MockService_StartScraper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_StartScraper_Call) RunAndReturn(run func(context.Context) error) *MockService_StartScraper_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlace provides a mock function with given fields: ctx, placeID, req
func (_m *MockService) UpdatePlace(ctx context.Context, placeID string, req generated.UpdatePlaceRequest) (*generated.Place, error) {
	ret := _m.Called(ctx, placeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdatePlaceRequest) (*generated.Place, error)); ok {
		return rf(ctx, placeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdatePlaceRequest) *generated.Place); ok {
		r0 = rf(ctx, placeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, generated.UpdatePlaceRequest) error); ok {
		r1 = rf(ctx, placeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlace'
type MockService_UpdatePlace_Call struct {
	*mock.Call
}

// UpdatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
//   - req generated.UpdatePlaceRequest
func (_e *MockService_Expecter) UpdatePlace(ctx interface{}, placeID interface{}, req interface{}) *MockService_UpdatePlace_Call {
	return &MockService_UpdatePlace_Call{Call: _e.mock.On("UpdatePlace", ctx, placeID, req)}
}

func (_c *MockService_UpdatePlace_Call) Run(run func(ctx context.Context, placeID string, req generated.UpdatePlaceRequest)) *MockService_UpdatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(generated.UpdatePlaceRequest))
	})
	return _c
}

func (_c *MockService_UpdatePlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_UpdatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdatePlace_Call) RunAndReturn(run func(context.Context, string, generated.UpdatePlaceRequest) (*generated.Place, error)) *MockService_UpdatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRetailListing provides a mock function with given fields: ctx, id, req
func (_m *MockService) UpdateRetailListing(ctx context.Context, id string, req generated.UpdateRetailListingRequest) (*generated.RetailListing, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRetailListing")
	}

	var r0 *generated.RetailListing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdateRetailListingRequest) (*generated.RetailListing, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdateRetailListingRequest) *generated.RetailListing); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.RetailListing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, generated.UpdateRetailListingRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRetailListing'
type MockService_UpdateRetailListing_Call struct {
	*mock.Call
}

// UpdateRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req generated.UpdateRetailListingRequest
func (_e *MockService_Expecter) UpdateRetailListing(ctx interface{}, id interface{}, req interface{}) *MockService_UpdateRetailListing_Call {
	return &MockService_UpdateRetailListing_Call{Call: _e.mock.On("UpdateRetailListing", ctx, id, req)}
}

func (_c *MockService_UpdateRetailListing_Call) Run(run func(ctx context.Context, id string, req generated.UpdateRetailListingRequest)) *MockService_UpdateRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(generated.UpdateRetailListingRequest))
	})
	return _c
}

func (_c *MockService_UpdateRetailListing_Call) Return(_a0 *generated.RetailListing, _a1 error) *MockService_UpdateRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateRetailListing_Call) RunAndReturn(run func(context.Context, string, generated.UpdateRetailListingRequest) (*generated.RetailListing, error)) *MockService_UpdateRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
