// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"

	pgtype "github.com/jackc/pgx/v5/pgtype"

	store "github.com/neofyis/geopulse/internal/store"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// BulkInsertSofiaplanFeatures provides a mock function with given fields: ctx, sql, propsJSON, geomJSON
func (_m *MockStore) BulkInsertSofiaplanFeatures(ctx context.Context, sql string, propsJSON []string, geomJSON []string) error {
	ret := _m.Called(ctx, sql, propsJSON, geomJSON)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsertSofiaplanFeatures")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, []string) error); ok {
		r0 = rf(ctx, sql, propsJSON, geomJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkInsertSofiaplanFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsertSofiaplanFeatures'
type MockStore_BulkInsertSofiaplanFeatures_Call struct {
	*mock.Call
}

// BulkInsertSofiaplanFeatures is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - propsJSON []string
//   - geomJSON []string
func (_e *MockStore_Expecter) BulkInsertSofiaplanFeatures(ctx interface{}, sql interface{}, propsJSON interface{}, geomJSON interface{}) *MockStore_BulkInsertSofiaplanFeatures_Call {
	return &MockStore_BulkInsertSofiaplanFeatures_Call{Call: _e.mock.On("BulkInsertSofiaplanFeatures", ctx, sql, propsJSON, geomJSON)}
}

func (_c *MockStore_BulkInsertSofiaplanFeatures_Call) Run(run func(ctx context.Context, sql string, propsJSON []string, geomJSON []string)) *MockStore_BulkInsertSofiaplanFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string), args[3].([]string))
	})
	return _c
}

func (_c *MockStore_BulkInsertSofiaplanFeatures_Call) Return(_a0 error) *MockStore_BulkInsertSofiaplanFeatures_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkInsertSofiaplanFeatures_Call) RunAndReturn(run func(context.Context, string, []string, []string) error) *MockStore_BulkInsertSofiaplanFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsertEdges provides a mock function with given fields: ctx, edges
func (_m *MockStore) BulkUpsertEdges(ctx context.Context, edges []store.OSMEdge) error {
	ret := _m.Called(ctx, edges)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertEdges")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMEdge) error); ok {
		r0 = rf(ctx, edges)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertEdges'
type MockStore_BulkUpsertEdges_Call struct {
	*mock.Call
}

// BulkUpsertEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - edges []store.OSMEdge
func (_e *MockStore_Expecter) BulkUpsertEdges(ctx interface{}, edges interface{}) *MockStore_BulkUpsertEdges_Call {
	return &MockStore_BulkUpsertEdges_Call{Call: _e.mock.On("BulkUpsertEdges", ctx, edges)}
}

func (_c *MockStore_BulkUpsertEdges_Call) Run(run func(ctx context.Context, edges []store.OSMEdge)) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMEdge))
	})
	return _c
}

func (_c *MockStore_BulkUpsertEdges_Call) Return(_a0 error) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertEdges_Call) RunAndReturn(run func(context.Context, []store.OSMEdge) error) *MockStore_BulkUpsertEdges_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsertNodes provides a mock function with given fields: ctx, nodes
func (_m *MockStore) BulkUpsertNodes(ctx context.Context, nodes []store.OSMNode) error {
	ret := _m.Called(ctx, nodes)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertNodes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMNode) error); ok {
		r0 = rf(ctx, nodes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertNodes'
type MockStore_BulkUpsertNodes_Call struct {
	*mock.Call
}

// BulkUpsertNodes is a helper method to define mock.On call
//   - ctx context.Context
//   - nodes []store.OSMNode
func (_e *MockStore_Expecter) BulkUpsertNodes(ctx interface{}, nodes interface{}) *MockStore_BulkUpsertNodes_Call {
	return &MockStore_BulkUpsertNodes_Call{Call: _e.mock.On("BulkUpsertNodes", ctx, nodes)}
}

func (_c *MockStore_BulkUpsertNodes_Call) Run(run func(ctx context.Context, nodes []store.OSMNode)) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMNode))
	})
	return _c
}

func (_c *MockStore_BulkUpsertNodes_Call) Return(_a0 error) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertNodes_Call) RunAndReturn(run func(context.Context, []store.OSMNode) error) *MockStore_BulkUpsertNodes_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpsertPOIs provides a mock function with given fields: ctx, pois
func (_m *MockStore) BulkUpsertPOIs(ctx context.Context, pois []store.OSMPOI) error {
	ret := _m.Called(ctx, pois)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsertPOIs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.OSMPOI) error); ok {
		r0 = rf(ctx, pois)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_BulkUpsertPOIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsertPOIs'
type MockStore_BulkUpsertPOIs_Call struct {
	*mock.Call
}

// BulkUpsertPOIs is a helper method to define mock.On call
//   - ctx context.Context
//   - pois []store.OSMPOI
func (_e *MockStore_Expecter) BulkUpsertPOIs(ctx interface{}, pois interface{}) *MockStore_BulkUpsertPOIs_Call {
	return &MockStore_BulkUpsertPOIs_Call{Call: _e.mock.On("BulkUpsertPOIs", ctx, pois)}
}

func (_c *MockStore_BulkUpsertPOIs_Call) Run(run func(ctx context.Context, pois []store.OSMPOI)) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.OSMPOI))
	})
	return _c
}

func (_c *MockStore_BulkUpsertPOIs_Call) Return(_a0 error) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_BulkUpsertPOIs_Call) RunAndReturn(run func(context.Context, []store.OSMPOI) error) *MockStore_BulkUpsertPOIs_Call {
	_c.Call.Return(run)
	return _c
}

// ComputeWalkScores provides a mock function with given fields: ctx
func (_m *MockStore) ComputeWalkScores(ctx context.Context) ([]store.NodeScore, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ComputeWalkScores")
	}

	var r0 []store.NodeScore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.NodeScore, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.NodeScore); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.NodeScore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ComputeWalkScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ComputeWalkScores'
type MockStore_ComputeWalkScores_Call struct {
	*mock.Call
}

// ComputeWalkScores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ComputeWalkScores(ctx interface{}) *MockStore_ComputeWalkScores_Call {
	return &MockStore_ComputeWalkScores_Call{Call: _e.mock.On("ComputeWalkScores", ctx)}
}

func (_c *MockStore_ComputeWalkScores_Call) Run(run func(ctx context.Context)) *MockStore_ComputeWalkScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ComputeWalkScores_Call) Return(_a0 []store.NodeScore, _a1 error) *MockStore_ComputeWalkScores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ComputeWalkScores_Call) RunAndReturn(run func(context.Context) ([]store.NodeScore, error)) *MockStore_ComputeWalkScores_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreatePlace(ctx context.Context, arg store.CreatePlaceParams) (store.CreatePlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlace")
	}

	var r0 store.CreatePlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.CreatePlaceParams) (store.CreatePlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.CreatePlaceParams) store.CreatePlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.CreatePlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.CreatePlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlace'
type MockStore_CreatePlace_Call struct {
	*mock.Call
}

// CreatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.CreatePlaceParams
func (_e *MockStore_Expecter) CreatePlace(ctx interface{}, arg interface{}) *MockStore_CreatePlace_Call {
	return &MockStore_CreatePlace_Call{Call: _e.mock.On("CreatePlace", ctx, arg)}
}

func (_c *MockStore_CreatePlace_Call) Run(run func(ctx context.Context, arg store.CreatePlaceParams)) *MockStore_CreatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.CreatePlaceParams))
	})
	return _c
}

func (_c *MockStore_CreatePlace_Call) Return(_a0 store.CreatePlaceRow, _a1 error) *MockStore_CreatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreatePlace_Call) RunAndReturn(run func(context.Context, store.CreatePlaceParams) (store.CreatePlaceRow, error)) *MockStore_CreatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRetailListing provides a mock function with given fields: ctx, arg
func (_m *MockStore) CreateRetailListing(ctx context.Context, arg store.CreateRetailListingParams) (store.CreateRetailListingRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateRetailListing")
	}

	var r0 store.CreateRetailListingRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.CreateRetailListingParams) (store.CreateRetailListingRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.CreateRetailListingParams) store.CreateRetailListingRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.CreateRetailListingRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.CreateRetailListingParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_CreateRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRetailListing'
type MockStore_CreateRetailListing_Call struct {
	*mock.Call
}

// CreateRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.CreateRetailListingParams
func (_e *MockStore_Expecter) CreateRetailListing(ctx interface{}, arg interface{}) *MockStore_CreateRetailListing_Call {
	return &MockStore_CreateRetailListing_Call{Call: _e.mock.On("CreateRetailListing", ctx, arg)}
}

func (_c *MockStore_CreateRetailListing_Call) Run(run func(ctx context.Context, arg store.CreateRetailListingParams)) *MockStore_CreateRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.CreateRetailListingParams))
	})
	return _c
}

func (_c *MockStore_CreateRetailListing_Call) Return(_a0 store.CreateRetailListingRow, _a1 error) *MockStore_CreateRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_CreateRetailListing_Call) RunAndReturn(run func(context.Context, store.CreateRetailListingParams) (store.CreateRetailListingRow, error)) *MockStore_CreateRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlace provides a mock function with given fields: ctx, placeID
func (_m *MockStore) DeletePlace(ctx context.Context, placeID string) error {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeletePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlace'
type MockStore_DeletePlace_Call struct {
	*mock.Call
}

// DeletePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockStore_Expecter) DeletePlace(ctx interface{}, placeID interface{}) *MockStore_DeletePlace_Call {
	return &MockStore_DeletePlace_Call{Call: _e.mock.On("DeletePlace", ctx, placeID)}
}

func (_c *MockStore_DeletePlace_Call) Run(run func(ctx context.Context, placeID string)) *MockStore_DeletePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_DeletePlace_Call) Return(_a0 error) *MockStore_DeletePlace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeletePlace_Call) RunAndReturn(run func(context.Context, string) error) *MockStore_DeletePlace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRetailListing provides a mock function with given fields: ctx, id
func (_m *MockStore) DeleteRetailListing(ctx context.Context, id pgtype.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRetailListing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_DeleteRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRetailListing'
type MockStore_DeleteRetailListing_Call struct {
	*mock.Call
}

// DeleteRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockStore_Expecter) DeleteRetailListing(ctx interface{}, id interface{}) *MockStore_DeleteRetailListing_Call {
	return &MockStore_DeleteRetailListing_Call{Call: _e.mock.On("DeleteRetailListing", ctx, id)}
}

func (_c *MockStore_DeleteRetailListing_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockStore_DeleteRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockStore_DeleteRetailListing_Call) Return(_a0 error) *MockStore_DeleteRetailListing_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_DeleteRetailListing_Call) RunAndReturn(run func(context.Context, pgtype.UUID) error) *MockStore_DeleteRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuildingDensityGeContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetBuildingDensityGeContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetBuildingDensityGeContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetBuildingDensityGeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuildingDensityGeContext'
type MockStore_GetBuildingDensityGeContext_Call struct {
	*mock.Call
}

// GetBuildingDensityGeContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetBuildingDensityGeContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetBuildingDensityGeContext_Call {
	return &MockStore_GetBuildingDensityGeContext_Call{Call: _e.mock.On("GetBuildingDensityGeContext", ctx, lng, lat)}
}

func (_c *MockStore_GetBuildingDensityGeContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetBuildingDensityGeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetBuildingDensityGeContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetBuildingDensityGeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetBuildingDensityGeContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetBuildingDensityGeContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuildingFootprintGeContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetBuildingFootprintGeContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetBuildingFootprintGeContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetBuildingFootprintGeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuildingFootprintGeContext'
type MockStore_GetBuildingFootprintGeContext_Call struct {
	*mock.Call
}

// GetBuildingFootprintGeContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetBuildingFootprintGeContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetBuildingFootprintGeContext_Call {
	return &MockStore_GetBuildingFootprintGeContext_Call{Call: _e.mock.On("GetBuildingFootprintGeContext", ctx, lng, lat)}
}

func (_c *MockStore_GetBuildingFootprintGeContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetBuildingFootprintGeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetBuildingFootprintGeContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetBuildingFootprintGeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetBuildingFootprintGeContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetBuildingFootprintGeContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetBusinessTurnoverContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetBusinessTurnoverContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetBusinessTurnoverContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetBusinessTurnoverContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBusinessTurnoverContext'
type MockStore_GetBusinessTurnoverContext_Call struct {
	*mock.Call
}

// GetBusinessTurnoverContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetBusinessTurnoverContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetBusinessTurnoverContext_Call {
	return &MockStore_GetBusinessTurnoverContext_Call{Call: _e.mock.On("GetBusinessTurnoverContext", ctx, lng, lat)}
}

func (_c *MockStore_GetBusinessTurnoverContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetBusinessTurnoverContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetBusinessTurnoverContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetBusinessTurnoverContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetBusinessTurnoverContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetBusinessTurnoverContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetDevelopmentPotentialContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetDevelopmentPotentialContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetDevelopmentPotentialContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetDevelopmentPotentialContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDevelopmentPotentialContext'
type MockStore_GetDevelopmentPotentialContext_Call struct {
	*mock.Call
}

// GetDevelopmentPotentialContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetDevelopmentPotentialContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetDevelopmentPotentialContext_Call {
	return &MockStore_GetDevelopmentPotentialContext_Call{Call: _e.mock.On("GetDevelopmentPotentialContext", ctx, lng, lat)}
}

func (_c *MockStore_GetDevelopmentPotentialContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetDevelopmentPotentialContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetDevelopmentPotentialContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetDevelopmentPotentialContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetDevelopmentPotentialContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetDevelopmentPotentialContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloodRiskHighContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetFloodRiskHighContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetFloodRiskHighContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetFloodRiskHighContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloodRiskHighContext'
type MockStore_GetFloodRiskHighContext_Call struct {
	*mock.Call
}

// GetFloodRiskHighContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetFloodRiskHighContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetFloodRiskHighContext_Call {
	return &MockStore_GetFloodRiskHighContext_Call{Call: _e.mock.On("GetFloodRiskHighContext", ctx, lng, lat)}
}

func (_c *MockStore_GetFloodRiskHighContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetFloodRiskHighContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetFloodRiskHighContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetFloodRiskHighContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetFloodRiskHighContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetFloodRiskHighContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloodRiskLowContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetFloodRiskLowContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetFloodRiskLowContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetFloodRiskLowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloodRiskLowContext'
type MockStore_GetFloodRiskLowContext_Call struct {
	*mock.Call
}

// GetFloodRiskLowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetFloodRiskLowContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetFloodRiskLowContext_Call {
	return &MockStore_GetFloodRiskLowContext_Call{Call: _e.mock.On("GetFloodRiskLowContext", ctx, lng, lat)}
}

func (_c *MockStore_GetFloodRiskLowContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetFloodRiskLowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetFloodRiskLowContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetFloodRiskLowContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetFloodRiskLowContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetFloodRiskLowContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetFloodRiskMediumContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetFloodRiskMediumContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetFloodRiskMediumContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetFloodRiskMediumContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloodRiskMediumContext'
type MockStore_GetFloodRiskMediumContext_Call struct {
	*mock.Call
}

// GetFloodRiskMediumContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetFloodRiskMediumContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetFloodRiskMediumContext_Call {
	return &MockStore_GetFloodRiskMediumContext_Call{Call: _e.mock.On("GetFloodRiskMediumContext", ctx, lng, lat)}
}

func (_c *MockStore_GetFloodRiskMediumContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetFloodRiskMediumContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetFloodRiskMediumContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetFloodRiskMediumContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetFloodRiskMediumContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetFloodRiskMediumContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatmap provides a mock function with given fields: ctx, p
func (_m *MockStore) GetHeatmap(ctx context.Context, p store.HeatmapParams) ([]store.HeatmapRow, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatmap")
	}

	var r0 []store.HeatmapRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.HeatmapParams) ([]store.HeatmapRow, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.HeatmapParams) []store.HeatmapRow); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.HeatmapRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.HeatmapParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetHeatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatmap'
type MockStore_GetHeatmap_Call struct {
	*mock.Call
}

// GetHeatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - p store.HeatmapParams
func (_e *MockStore_Expecter) GetHeatmap(ctx interface{}, p interface{}) *MockStore_GetHeatmap_Call {
	return &MockStore_GetHeatmap_Call{Call: _e.mock.On("GetHeatmap", ctx, p)}
}

func (_c *MockStore_GetHeatmap_Call) Run(run func(ctx context.Context, p store.HeatmapParams)) *MockStore_GetHeatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.HeatmapParams))
	})
	return _c
}

func (_c *MockStore_GetHeatmap_Call) Return(_a0 []store.HeatmapRow, _a1 error) *MockStore_GetHeatmap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetHeatmap_Call) RunAndReturn(run func(context.Context, store.HeatmapParams) ([]store.HeatmapRow, error)) *MockStore_GetHeatmap_Call {
	_c.Call.Return(run)
	return _c
}

// GetIncomeContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetIncomeContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetIncomeContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetIncomeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIncomeContext'
type MockStore_GetIncomeContext_Call struct {
	*mock.Call
}

// GetIncomeContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetIncomeContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetIncomeContext_Call {
	return &MockStore_GetIncomeContext_Call{Call: _e.mock.On("GetIncomeContext", ctx, lng, lat)}
}

func (_c *MockStore_GetIncomeContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetIncomeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetIncomeContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetIncomeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetIncomeContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetIncomeContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroCatchmentContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetMetroCatchmentContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, bool, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroCatchmentContext")
	}

	var r0 json.RawMessage
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, bool, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) bool); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, float64, float64) error); ok {
		r2 = rf(ctx, lng, lat)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_GetMetroCatchmentContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroCatchmentContext'
type MockStore_GetMetroCatchmentContext_Call struct {
	*mock.Call
}

// GetMetroCatchmentContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetMetroCatchmentContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetMetroCatchmentContext_Call {
	return &MockStore_GetMetroCatchmentContext_Call{Call: _e.mock.On("GetMetroCatchmentContext", ctx, lng, lat)}
}

func (_c *MockStore_GetMetroCatchmentContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetMetroCatchmentContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetMetroCatchmentContext_Call) Return(_a0 json.RawMessage, _a1 bool, _a2 error) *MockStore_GetMetroCatchmentContext_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_GetMetroCatchmentContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, bool, error)) *MockStore_GetMetroCatchmentContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroStops provides a mock function with given fields: ctx
func (_m *MockStore) GetMetroStops(ctx context.Context) ([]store.GetMetroStopsRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroStops")
	}

	var r0 []store.GetMetroStopsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.GetMetroStopsRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.GetMetroStopsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.GetMetroStopsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetMetroStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroStops'
type MockStore_GetMetroStops_Call struct {
	*mock.Call
}

// GetMetroStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetMetroStops(ctx interface{}) *MockStore_GetMetroStops_Call {
	return &MockStore_GetMetroStops_Call{Call: _e.mock.On("GetMetroStops", ctx)}
}

func (_c *MockStore_GetMetroStops_Call) Run(run func(ctx context.Context)) *MockStore_GetMetroStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetMetroStops_Call) Return(_a0 []store.GetMetroStopsRow, _a1 error) *MockStore_GetMetroStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetMetroStops_Call) RunAndReturn(run func(context.Context) ([]store.GetMetroStopsRow, error)) *MockStore_GetMetroStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroStations provides a mock function with given fields: ctx
func (_m *MockStore) GetMetroStations(ctx context.Context) ([]store.MetroStationRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroStations")
	}

	var r0 []store.MetroStationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.MetroStationRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.MetroStationRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.MetroStationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetMetroStations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroStations'
type MockStore_GetMetroStations_Call struct {
	*mock.Call
}

// GetMetroStations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetMetroStations(ctx interface{}) *MockStore_GetMetroStations_Call {
	return &MockStore_GetMetroStations_Call{Call: _e.mock.On("GetMetroStations", ctx)}
}

func (_c *MockStore_GetMetroStations_Call) Run(run func(ctx context.Context)) *MockStore_GetMetroStations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetMetroStations_Call) Return(_a0 []store.MetroStationRow, _a1 error) *MockStore_GetMetroStations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetMetroStations_Call) RunAndReturn(run func(context.Context) ([]store.MetroStationRow, error)) *MockStore_GetMetroStations_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitStops provides a mock function with given fields: ctx
func (_m *MockStore) GetTransitStops(ctx context.Context) ([]store.TransitStopRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitStops")
	}

	var r0 []store.TransitStopRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.TransitStopRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.TransitStopRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.TransitStopRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetTransitStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitStops'
type MockStore_GetTransitStops_Call struct {
	*mock.Call
}

// GetTransitStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) GetTransitStops(ctx interface{}) *MockStore_GetTransitStops_Call {
	return &MockStore_GetTransitStops_Call{Call: _e.mock.On("GetTransitStops", ctx)}
}

func (_c *MockStore_GetTransitStops_Call) Run(run func(ctx context.Context)) *MockStore_GetTransitStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_GetTransitStops_Call) Return(_a0 []store.TransitStopRow, _a1 error) *MockStore_GetTransitStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetTransitStops_Call) RunAndReturn(run func(context.Context) ([]store.TransitStopRow, error)) *MockStore_GetTransitStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetNeighborhoodContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetNeighborhoodContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetNeighborhoodContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetNeighborhoodContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNeighborhoodContext'
type MockStore_GetNeighborhoodContext_Call struct {
	*mock.Call
}

// GetNeighborhoodContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetNeighborhoodContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetNeighborhoodContext_Call {
	return &MockStore_GetNeighborhoodContext_Call{Call: _e.mock.On("GetNeighborhoodContext", ctx, lng, lat)}
}

func (_c *MockStore_GetNeighborhoodContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetNeighborhoodContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetNeighborhoodContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetNeighborhoodContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetNeighborhoodContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetNeighborhoodContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetPedestrianContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetPedestrianContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetPedestrianContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetPedestrianContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPedestrianContext'
type MockStore_GetPedestrianContext_Call struct {
	*mock.Call
}

// GetPedestrianContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetPedestrianContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetPedestrianContext_Call {
	return &MockStore_GetPedestrianContext_Call{Call: _e.mock.On("GetPedestrianContext", ctx, lng, lat)}
}

func (_c *MockStore_GetPedestrianContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetPedestrianContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetPedestrianContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetPedestrianContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetPedestrianContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetPedestrianContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlace provides a mock function with given fields: ctx, placeID
func (_m *MockStore) GetPlace(ctx context.Context, placeID string) (store.GetPlaceRow, error) {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlace")
	}

	var r0 store.GetPlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (store.GetPlaceRow, error)); ok {
		return rf(ctx, placeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) store.GetPlaceRow); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Get(0).(store.GetPlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlace'
type MockStore_GetPlace_Call struct {
	*mock.Call
}

// GetPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockStore_Expecter) GetPlace(ctx interface{}, placeID interface{}) *MockStore_GetPlace_Call {
	return &MockStore_GetPlace_Call{Call: _e.mock.On("GetPlace", ctx, placeID)}
}

func (_c *MockStore_GetPlace_Call) Run(run func(ctx context.Context, placeID string)) *MockStore_GetPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_GetPlace_Call) Return(_a0 store.GetPlaceRow, _a1 error) *MockStore_GetPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetPlace_Call) RunAndReturn(run func(context.Context, string) (store.GetPlaceRow, error)) *MockStore_GetPlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetPopulationContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetPopulationContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetPopulationContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetPopulationContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPopulationContext'
type MockStore_GetPopulationContext_Call struct {
	*mock.Call
}

// GetPopulationContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetPopulationContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetPopulationContext_Call {
	return &MockStore_GetPopulationContext_Call{Call: _e.mock.On("GetPopulationContext", ctx, lng, lat)}
}

func (_c *MockStore_GetPopulationContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetPopulationContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetPopulationContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetPopulationContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetPopulationContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetPopulationContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyPriceContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetPropertyPriceContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyPriceContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetPropertyPriceContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyPriceContext'
type MockStore_GetPropertyPriceContext_Call struct {
	*mock.Call
}

// GetPropertyPriceContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetPropertyPriceContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetPropertyPriceContext_Call {
	return &MockStore_GetPropertyPriceContext_Call{Call: _e.mock.On("GetPropertyPriceContext", ctx, lng, lat)}
}

func (_c *MockStore_GetPropertyPriceContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetPropertyPriceContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetPropertyPriceContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetPropertyPriceContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetPropertyPriceContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetPropertyPriceContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetResidentialTypologyGeContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetResidentialTypologyGeContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetResidentialTypologyGeContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetResidentialTypologyGeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResidentialTypologyGeContext'
type MockStore_GetResidentialTypologyGeContext_Call struct {
	*mock.Call
}

// GetResidentialTypologyGeContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetResidentialTypologyGeContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetResidentialTypologyGeContext_Call {
	return &MockStore_GetResidentialTypologyGeContext_Call{Call: _e.mock.On("GetResidentialTypologyGeContext", ctx, lng, lat)}
}

func (_c *MockStore_GetResidentialTypologyGeContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetResidentialTypologyGeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetResidentialTypologyGeContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetResidentialTypologyGeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetResidentialTypologyGeContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetResidentialTypologyGeContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetailListing provides a mock function with given fields: ctx, id
func (_m *MockStore) GetRetailListing(ctx context.Context, id pgtype.UUID) (store.GetRetailListingRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRetailListing")
	}

	var r0 store.GetRetailListingRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (store.GetRetailListingRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) store.GetRetailListingRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(store.GetRetailListingRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetailListing'
type MockStore_GetRetailListing_Call struct {
	*mock.Call
}

// GetRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockStore_Expecter) GetRetailListing(ctx interface{}, id interface{}) *MockStore_GetRetailListing_Call {
	return &MockStore_GetRetailListing_Call{Call: _e.mock.On("GetRetailListing", ctx, id)}
}

func (_c *MockStore_GetRetailListing_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockStore_GetRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.UUID))
	})
	return _c
}

func (_c *MockStore_GetRetailListing_Call) Return(_a0 store.GetRetailListingRow, _a1 error) *MockStore_GetRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetRetailListing_Call) RunAndReturn(run func(context.Context, pgtype.UUID) (store.GetRetailListingRow, error)) *MockStore_GetRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// GetSaturation provides a mock function with given fields: ctx, p
func (_m *MockStore) GetSaturation(ctx context.Context, p store.SaturationParams) (store.SaturationRow, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for GetSaturation")
	}

	var r0 store.SaturationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.SaturationParams) (store.SaturationRow, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.SaturationParams) store.SaturationRow); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(store.SaturationRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.SaturationParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetSaturation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSaturation'
type MockStore_GetSaturation_Call struct {
	*mock.Call
}

// GetSaturation is a helper method to define mock.On call
//   - ctx context.Context
//   - p store.SaturationParams
func (_e *MockStore_Expecter) GetSaturation(ctx interface{}, p interface{}) *MockStore_GetSaturation_Call {
	return &MockStore_GetSaturation_Call{Call: _e.mock.On("GetSaturation", ctx, p)}
}

func (_c *MockStore_GetSaturation_Call) Run(run func(ctx context.Context, p store.SaturationParams)) *MockStore_GetSaturation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.SaturationParams))
	})
	return _c
}

func (_c *MockStore_GetSaturation_Call) Return(_a0 store.SaturationRow, _a1 error) *MockStore_GetSaturation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetSaturation_Call) RunAndReturn(run func(context.Context, store.SaturationParams) (store.SaturationRow, error)) *MockStore_GetSaturation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUrbanMorphologyGeContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetUrbanMorphologyGeContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetUrbanMorphologyGeContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUrbanMorphologyGeContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUrbanMorphologyGeContext'
type MockStore_GetUrbanMorphologyGeContext_Call struct {
	*mock.Call
}

// GetUrbanMorphologyGeContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetUrbanMorphologyGeContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetUrbanMorphologyGeContext_Call {
	return &MockStore_GetUrbanMorphologyGeContext_Call{Call: _e.mock.On("GetUrbanMorphologyGeContext", ctx, lng, lat)}
}

func (_c *MockStore_GetUrbanMorphologyGeContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetUrbanMorphologyGeContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetUrbanMorphologyGeContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetUrbanMorphologyGeContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUrbanMorphologyGeContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetUrbanMorphologyGeContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetZoningContext provides a mock function with given fields: ctx, lng, lat
func (_m *MockStore) GetZoningContext(ctx context.Context, lng float64, lat float64) (json.RawMessage, error) {
	ret := _m.Called(ctx, lng, lat)

	if len(ret) == 0 {
		panic("no return value specified for GetZoningContext")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) (json.RawMessage, error)); ok {
		return rf(ctx, lng, lat)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64) json.RawMessage); ok {
		r0 = rf(ctx, lng, lat)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64) error); ok {
		r1 = rf(ctx, lng, lat)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetZoningContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetZoningContext'
type MockStore_GetZoningContext_Call struct {
	*mock.Call
}

// GetZoningContext is a helper method to define mock.On call
//   - ctx context.Context
//   - lng float64
//   - lat float64
func (_e *MockStore_Expecter) GetZoningContext(ctx interface{}, lng interface{}, lat interface{}) *MockStore_GetZoningContext_Call {
	return &MockStore_GetZoningContext_Call{Call: _e.mock.On("GetZoningContext", ctx, lng, lat)}
}

func (_c *MockStore_GetZoningContext_Call) Run(run func(ctx context.Context, lng float64, lat float64)) *MockStore_GetZoningContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64))
	})
	return _c
}

func (_c *MockStore_GetZoningContext_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_GetZoningContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetZoningContext_Call) RunAndReturn(run func(context.Context, float64, float64) (json.RawMessage, error)) *MockStore_GetZoningContext_Call {
	_c.Call.Return(run)
	return _c
}

// ListNeighborhoodNames provides a mock function with given fields: ctx
func (_m *MockStore) ListNeighborhoodNames(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNeighborhoodNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListNeighborhoodNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNeighborhoodNames'
type MockStore_ListNeighborhoodNames_Call struct {
	*mock.Call
}

// ListNeighborhoodNames is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListNeighborhoodNames(ctx interface{}) *MockStore_ListNeighborhoodNames_Call {
	return &MockStore_ListNeighborhoodNames_Call{Call: _e.mock.On("ListNeighborhoodNames", ctx)}
}

func (_c *MockStore_ListNeighborhoodNames_Call) Run(run func(ctx context.Context)) *MockStore_ListNeighborhoodNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListNeighborhoodNames_Call) Return(_a0 []string, _a1 error) *MockStore_ListNeighborhoodNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListNeighborhoodNames_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockStore_ListNeighborhoodNames_Call {
	_c.Call.Return(run)
	return _c
}

// ListParkingZones provides a mock function with given fields: ctx
func (_m *MockStore) ListParkingZones(ctx context.Context) ([]store.ParkingZone, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListParkingZones")
	}

	var r0 []store.ParkingZone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ParkingZone, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ParkingZone); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ParkingZone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListParkingZones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParkingZones'
type MockStore_ListParkingZones_Call struct {
	*mock.Call
}

// ListParkingZones is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListParkingZones(ctx interface{}) *MockStore_ListParkingZones_Call {
	return &MockStore_ListParkingZones_Call{Call: _e.mock.On("ListParkingZones", ctx)}
}

func (_c *MockStore_ListParkingZones_Call) Run(run func(ctx context.Context)) *MockStore_ListParkingZones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListParkingZones_Call) Return(_a0 []store.ParkingZone, _a1 error) *MockStore_ListParkingZones_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListParkingZones_Call) RunAndReturn(run func(context.Context) ([]store.ParkingZone, error)) *MockStore_ListParkingZones_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlaces provides a mock function with given fields: ctx
func (_m *MockStore) ListPlaces(ctx context.Context) ([]store.ListPlacesRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlaces")
	}

	var r0 []store.ListPlacesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ListPlacesRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ListPlacesRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlaces'
type MockStore_ListPlaces_Call struct {
	*mock.Call
}

// ListPlaces is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListPlaces(ctx interface{}) *MockStore_ListPlaces_Call {
	return &MockStore_ListPlaces_Call{Call: _e.mock.On("ListPlaces", ctx)}
}

func (_c *MockStore_ListPlaces_Call) Run(run func(ctx context.Context)) *MockStore_ListPlaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListPlaces_Call) Return(_a0 []store.ListPlacesRow, _a1 error) *MockStore_ListPlaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlaces_Call) RunAndReturn(run func(context.Context) ([]store.ListPlacesRow, error)) *MockStore_ListPlaces_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByCategory provides a mock function with given fields: ctx, category
func (_m *MockStore) ListPlacesByCategory(ctx context.Context, category pgtype.Text) ([]store.ListPlacesByCategoryRow, error) {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByCategory")
	}

	var r0 []store.ListPlacesByCategoryRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) ([]store.ListPlacesByCategoryRow, error)); ok {
		return rf(ctx, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.Text) []store.ListPlacesByCategoryRow); ok {
		r0 = rf(ctx, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByCategoryRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.Text) error); ok {
		r1 = rf(ctx, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByCategory'
type MockStore_ListPlacesByCategory_Call struct {
	*mock.Call
}

// ListPlacesByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category pgtype.Text
func (_e *MockStore_Expecter) ListPlacesByCategory(ctx interface{}, category interface{}) *MockStore_ListPlacesByCategory_Call {
	return &MockStore_ListPlacesByCategory_Call{Call: _e.mock.On("ListPlacesByCategory", ctx, category)}
}

func (_c *MockStore_ListPlacesByCategory_Call) Run(run func(ctx context.Context, category pgtype.Text)) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pgtype.Text))
	})
	return _c
}

func (_c *MockStore_ListPlacesByCategory_Call) Return(_a0 []store.ListPlacesByCategoryRow, _a1 error) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByCategory_Call) RunAndReturn(run func(context.Context, pgtype.Text) ([]store.ListPlacesByCategoryRow, error)) *MockStore_ListPlacesByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByCategoryAndTag provides a mock function with given fields: ctx, arg
func (_m *MockStore) ListPlacesByCategoryAndTag(ctx context.Context, arg store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByCategoryAndTag")
	}

	var r0 []store.ListPlacesByCategoryAndTagRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.ListPlacesByCategoryAndTagParams) []store.ListPlacesByCategoryAndTagRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByCategoryAndTagRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.ListPlacesByCategoryAndTagParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByCategoryAndTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByCategoryAndTag'
type MockStore_ListPlacesByCategoryAndTag_Call struct {
	*mock.Call
}

// ListPlacesByCategoryAndTag is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.ListPlacesByCategoryAndTagParams
func (_e *MockStore_Expecter) ListPlacesByCategoryAndTag(ctx interface{}, arg interface{}) *MockStore_ListPlacesByCategoryAndTag_Call {
	return &MockStore_ListPlacesByCategoryAndTag_Call{Call: _e.mock.On("ListPlacesByCategoryAndTag", ctx, arg)}
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) Run(run func(ctx context.Context, arg store.ListPlacesByCategoryAndTagParams)) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.ListPlacesByCategoryAndTagParams))
	})
	return _c
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) Return(_a0 []store.ListPlacesByCategoryAndTagRow, _a1 error) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByCategoryAndTag_Call) RunAndReturn(run func(context.Context, store.ListPlacesByCategoryAndTagParams) ([]store.ListPlacesByCategoryAndTagRow, error)) *MockStore_ListPlacesByCategoryAndTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesByTag provides a mock function with given fields: ctx, dollar_1
func (_m *MockStore) ListPlacesByTag(ctx context.Context, dollar_1 string) ([]store.ListPlacesByTagRow, error) {
	ret := _m.Called(ctx, dollar_1)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesByTag")
	}

	var r0 []store.ListPlacesByTagRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.ListPlacesByTagRow, error)); ok {
		return rf(ctx, dollar_1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.ListPlacesByTagRow); ok {
		r0 = rf(ctx, dollar_1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesByTagRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dollar_1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesByTag'
type MockStore_ListPlacesByTag_Call struct {
	*mock.Call
}

// ListPlacesByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - dollar_1 string
func (_e *MockStore_Expecter) ListPlacesByTag(ctx interface{}, dollar_1 interface{}) *MockStore_ListPlacesByTag_Call {
	return &MockStore_ListPlacesByTag_Call{Call: _e.mock.On("ListPlacesByTag", ctx, dollar_1)}
}

func (_c *MockStore_ListPlacesByTag_Call) Run(run func(ctx context.Context, dollar_1 string)) *MockStore_ListPlacesByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_ListPlacesByTag_Call) Return(_a0 []store.ListPlacesByTagRow, _a1 error) *MockStore_ListPlacesByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesByTag_Call) RunAndReturn(run func(context.Context, string) ([]store.ListPlacesByTagRow, error)) *MockStore_ListPlacesByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlacesNeedingEnrichment provides a mock function with given fields: ctx
func (_m *MockStore) ListPlacesNeedingEnrichment(ctx context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPlacesNeedingEnrichment")
	}

	var r0 []store.ListPlacesNeedingEnrichmentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ListPlacesNeedingEnrichmentRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListPlacesNeedingEnrichmentRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListPlacesNeedingEnrichment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlacesNeedingEnrichment'
type MockStore_ListPlacesNeedingEnrichment_Call struct {
	*mock.Call
}

// ListPlacesNeedingEnrichment is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListPlacesNeedingEnrichment(ctx interface{}) *MockStore_ListPlacesNeedingEnrichment_Call {
	return &MockStore_ListPlacesNeedingEnrichment_Call{Call: _e.mock.On("ListPlacesNeedingEnrichment", ctx)}
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) Run(run func(ctx context.Context)) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) Return(_a0 []store.ListPlacesNeedingEnrichmentRow, _a1 error) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListPlacesNeedingEnrichment_Call) RunAndReturn(run func(context.Context) ([]store.ListPlacesNeedingEnrichmentRow, error)) *MockStore_ListPlacesNeedingEnrichment_Call {
	_c.Call.Return(run)
	return _c
}

// ListRetailListings provides a mock function with given fields: ctx
func (_m *MockStore) ListRetailListings(ctx context.Context) ([]store.ListRetailListingsRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRetailListings")
	}

	var r0 []store.ListRetailListingsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.ListRetailListingsRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.ListRetailListingsRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.ListRetailListingsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListRetailListings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRetailListings'
type MockStore_ListRetailListings_Call struct {
	*mock.Call
}

// ListRetailListings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListRetailListings(ctx interface{}) *MockStore_ListRetailListings_Call {
	return &MockStore_ListRetailListings_Call{Call: _e.mock.On("ListRetailListings", ctx)}
}

func (_c *MockStore_ListRetailListings_Call) Run(run func(ctx context.Context)) *MockStore_ListRetailListings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListRetailListings_Call) Return(_a0 []store.ListRetailListingsRow, _a1 error) *MockStore_ListRetailListings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListRetailListings_Call) RunAndReturn(run func(context.Context) ([]store.ListRetailListingsRow, error)) *MockStore_ListRetailListings_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdresLocations provides a mock function with given fields: ctx
func (_m *MockStore) ListAdresLocations(ctx context.Context) ([]store.AdresLocationRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAdresLocations")
	}

	var r0 []store.AdresLocationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.AdresLocationRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.AdresLocationRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.AdresLocationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListAdresLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdresLocations'
type MockStore_ListAdresLocations_Call struct {
	*mock.Call
}

// ListAdresLocations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListAdresLocations(ctx interface{}) *MockStore_ListAdresLocations_Call {
	return &MockStore_ListAdresLocations_Call{Call: _e.mock.On("ListAdresLocations", ctx)}
}

func (_c *MockStore_ListAdresLocations_Call) Run(run func(ctx context.Context)) *MockStore_ListAdresLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListAdresLocations_Call) Return(_a0 []store.AdresLocationRow, _a1 error) *MockStore_ListAdresLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListAdresLocations_Call) RunAndReturn(run func(context.Context) ([]store.AdresLocationRow, error)) *MockStore_ListAdresLocations_Call {
	_c.Call.Return(run)
	return _c
}

// ListBgPropertiesLocations provides a mock function with given fields: ctx
func (_m *MockStore) ListBgPropertiesLocations(ctx context.Context) ([]store.BgPropertiesLocationRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBgPropertiesLocations")
	}

	var r0 []store.BgPropertiesLocationRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]store.BgPropertiesLocationRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []store.BgPropertiesLocationRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.BgPropertiesLocationRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListBgPropertiesLocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBgPropertiesLocations'
type MockStore_ListBgPropertiesLocations_Call struct {
	*mock.Call
}

// ListBgPropertiesLocations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ListBgPropertiesLocations(ctx interface{}) *MockStore_ListBgPropertiesLocations_Call {
	return &MockStore_ListBgPropertiesLocations_Call{Call: _e.mock.On("ListBgPropertiesLocations", ctx)}
}

func (_c *MockStore_ListBgPropertiesLocations_Call) Run(run func(ctx context.Context)) *MockStore_ListBgPropertiesLocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ListBgPropertiesLocations_Call) Return(_a0 []store.BgPropertiesLocationRow, _a1 error) *MockStore_ListBgPropertiesLocations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListBgPropertiesLocations_Call) RunAndReturn(run func(context.Context) ([]store.BgPropertiesLocationRow, error)) *MockStore_ListBgPropertiesLocations_Call {
	_c.Call.Return(run)
	return _c
}

// ParkingZonesGeoJSON provides a mock function with given fields: ctx
func (_m *MockStore) ParkingZonesGeoJSON(ctx context.Context) (json.RawMessage, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ParkingZonesGeoJSON")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (json.RawMessage, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) json.RawMessage); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ParkingZonesGeoJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParkingZonesGeoJSON'
type MockStore_ParkingZonesGeoJSON_Call struct {
	*mock.Call
}

// ParkingZonesGeoJSON is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) ParkingZonesGeoJSON(ctx interface{}) *MockStore_ParkingZonesGeoJSON_Call {
	return &MockStore_ParkingZonesGeoJSON_Call{Call: _e.mock.On("ParkingZonesGeoJSON", ctx)}
}

func (_c *MockStore_ParkingZonesGeoJSON_Call) Run(run func(ctx context.Context)) *MockStore_ParkingZonesGeoJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_ParkingZonesGeoJSON_Call) Return(_a0 json.RawMessage, _a1 error) *MockStore_ParkingZonesGeoJSON_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ParkingZonesGeoJSON_Call) RunAndReturn(run func(context.Context) (json.RawMessage, error)) *MockStore_ParkingZonesGeoJSON_Call {
	_c.Call.Return(run)
	return _c
}

// PropagateEdgeScores provides a mock function with given fields: ctx
func (_m *MockStore) PropagateEdgeScores(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PropagateEdgeScores")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_PropagateEdgeScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PropagateEdgeScores'
type MockStore_PropagateEdgeScores_Call struct {
	*mock.Call
}

// PropagateEdgeScores is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStore_Expecter) PropagateEdgeScores(ctx interface{}) *MockStore_PropagateEdgeScores_Call {
	return &MockStore_PropagateEdgeScores_Call{Call: _e.mock.On("PropagateEdgeScores", ctx)}
}

func (_c *MockStore_PropagateEdgeScores_Call) Run(run func(ctx context.Context)) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStore_PropagateEdgeScores_Call) Return(_a0 error) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_PropagateEdgeScores_Call) RunAndReturn(run func(context.Context) error) *MockStore_PropagateEdgeScores_Call {
	_c.Call.Return(run)
	return _c
}

// TruncateSofiaplanTable provides a mock function with given fields: ctx, tableName
func (_m *MockStore) TruncateSofiaplanTable(ctx context.Context, tableName string) error {
	ret := _m.Called(ctx, tableName)

	if len(ret) == 0 {
		panic("no return value specified for TruncateSofiaplanTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tableName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_TruncateSofiaplanTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TruncateSofiaplanTable'
type MockStore_TruncateSofiaplanTable_Call struct {
	*mock.Call
}

// TruncateSofiaplanTable is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName string
func (_e *MockStore_Expecter) TruncateSofiaplanTable(ctx interface{}, tableName interface{}) *MockStore_TruncateSofiaplanTable_Call {
	return &MockStore_TruncateSofiaplanTable_Call{Call: _e.mock.On("TruncateSofiaplanTable", ctx, tableName)}
}

func (_c *MockStore_TruncateSofiaplanTable_Call) Run(run func(ctx context.Context, tableName string)) *MockStore_TruncateSofiaplanTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStore_TruncateSofiaplanTable_Call) Return(_a0 error) *MockStore_TruncateSofiaplanTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_TruncateSofiaplanTable_Call) RunAndReturn(run func(context.Context, string) error) *MockStore_TruncateSofiaplanTable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNodeWalkScores provides a mock function with given fields: ctx, scores
func (_m *MockStore) UpdateNodeWalkScores(ctx context.Context, scores []store.NodeScore) error {
	ret := _m.Called(ctx, scores)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNodeWalkScores")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []store.NodeScore) error); ok {
		r0 = rf(ctx, scores)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdateNodeWalkScores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNodeWalkScores'
type MockStore_UpdateNodeWalkScores_Call struct {
	*mock.Call
}

// UpdateNodeWalkScores is a helper method to define mock.On call
//   - ctx context.Context
//   - scores []store.NodeScore
func (_e *MockStore_Expecter) UpdateNodeWalkScores(ctx interface{}, scores interface{}) *MockStore_UpdateNodeWalkScores_Call {
	return &MockStore_UpdateNodeWalkScores_Call{Call: _e.mock.On("UpdateNodeWalkScores", ctx, scores)}
}

func (_c *MockStore_UpdateNodeWalkScores_Call) Run(run func(ctx context.Context, scores []store.NodeScore)) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]store.NodeScore))
	})
	return _c
}

func (_c *MockStore_UpdateNodeWalkScores_Call) Return(_a0 error) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdateNodeWalkScores_Call) RunAndReturn(run func(context.Context, []store.NodeScore) error) *MockStore_UpdateNodeWalkScores_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdatePlace(ctx context.Context, arg store.UpdatePlaceParams) (store.UpdatePlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlace")
	}

	var r0 store.UpdatePlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceParams) (store.UpdatePlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceParams) store.UpdatePlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.UpdatePlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UpdatePlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlace'
type MockStore_UpdatePlace_Call struct {
	*mock.Call
}

// UpdatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdatePlaceParams
func (_e *MockStore_Expecter) UpdatePlace(ctx interface{}, arg interface{}) *MockStore_UpdatePlace_Call {
	return &MockStore_UpdatePlace_Call{Call: _e.mock.On("UpdatePlace", ctx, arg)}
}

func (_c *MockStore_UpdatePlace_Call) Run(run func(ctx context.Context, arg store.UpdatePlaceParams)) *MockStore_UpdatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpdatePlaceParams))
	})
	return _c
}

func (_c *MockStore_UpdatePlace_Call) Return(_a0 store.UpdatePlaceRow, _a1 error) *MockStore_UpdatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdatePlace_Call) RunAndReturn(run func(context.Context, store.UpdatePlaceParams) (store.UpdatePlaceRow, error)) *MockStore_UpdatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlaceEnrichment provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdatePlaceEnrichment(ctx context.Context, arg store.UpdatePlaceEnrichmentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlaceEnrichment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdatePlaceEnrichmentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_UpdatePlaceEnrichment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlaceEnrichment'
type MockStore_UpdatePlaceEnrichment_Call struct {
	*mock.Call
}

// UpdatePlaceEnrichment is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdatePlaceEnrichmentParams
func (_e *MockStore_Expecter) UpdatePlaceEnrichment(ctx interface{}, arg interface{}) *MockStore_UpdatePlaceEnrichment_Call {
	return &MockStore_UpdatePlaceEnrichment_Call{Call: _e.mock.On("UpdatePlaceEnrichment", ctx, arg)}
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) Run(run func(ctx context.Context, arg store.UpdatePlaceEnrichmentParams)) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpdatePlaceEnrichmentParams))
	})
	return _c
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) Return(_a0 error) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_UpdatePlaceEnrichment_Call) RunAndReturn(run func(context.Context, store.UpdatePlaceEnrichmentParams) error) *MockStore_UpdatePlaceEnrichment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRetailListing provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpdateRetailListing(ctx context.Context, arg store.UpdateRetailListingParams) (store.UpdateRetailListingRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRetailListing")
	}

	var r0 store.UpdateRetailListingRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdateRetailListingParams) (store.UpdateRetailListingRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UpdateRetailListingParams) store.UpdateRetailListingRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.UpdateRetailListingRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UpdateRetailListingParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpdateRetailListing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRetailListing'
type MockStore_UpdateRetailListing_Call struct {
	*mock.Call
}

// UpdateRetailListing is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpdateRetailListingParams
func (_e *MockStore_Expecter) UpdateRetailListing(ctx interface{}, arg interface{}) *MockStore_UpdateRetailListing_Call {
	return &MockStore_UpdateRetailListing_Call{Call: _e.mock.On("UpdateRetailListing", ctx, arg)}
}

func (_c *MockStore_UpdateRetailListing_Call) Run(run func(ctx context.Context, arg store.UpdateRetailListingParams)) *MockStore_UpdateRetailListing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpdateRetailListingParams))
	})
	return _c
}

func (_c *MockStore_UpdateRetailListing_Call) Return(_a0 store.UpdateRetailListingRow, _a1 error) *MockStore_UpdateRetailListing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpdateRetailListing_Call) RunAndReturn(run func(context.Context, store.UpdateRetailListingParams) (store.UpdateRetailListingRow, error)) *MockStore_UpdateRetailListing_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPlace provides a mock function with given fields: ctx, arg
func (_m *MockStore) UpsertPlace(ctx context.Context, arg store.UpsertPlaceParams) (store.UpsertPlaceRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPlace")
	}

	var r0 store.UpsertPlaceRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, store.UpsertPlaceParams) (store.UpsertPlaceRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, store.UpsertPlaceParams) store.UpsertPlaceRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(store.UpsertPlaceRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, store.UpsertPlaceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_UpsertPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPlace'
type MockStore_UpsertPlace_Call struct {
	*mock.Call
}

// UpsertPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - arg store.UpsertPlaceParams
func (_e *MockStore_Expecter) UpsertPlace(ctx interface{}, arg interface{}) *MockStore_UpsertPlace_Call {
	return &MockStore_UpsertPlace_Call{Call: _e.mock.On("UpsertPlace", ctx, arg)}
}

func (_c *MockStore_UpsertPlace_Call) Run(run func(ctx context.Context, arg store.UpsertPlaceParams)) *MockStore_UpsertPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(store.UpsertPlaceParams))
	})
	return _c
}

func (_c *MockStore_UpsertPlace_Call) Return(_a0 store.UpsertPlaceRow, _a1 error) *MockStore_UpsertPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_UpsertPlace_Call) RunAndReturn(run func(context.Context, store.UpsertPlaceParams) (store.UpsertPlaceRow, error)) *MockStore_UpsertPlace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
