openapi: 3.0.0
info:
  title: Geopulse Backend
  version: 0.0.0
tags: []
paths:
  /enrich:
    post:
      operationId: Enrich_create
      summary: Trigger enricher
      description: Starts a background Google Places details enricher job.
      parameters: []
      responses:
        '202':
          description: The request has been accepted for processing, but processing has not yet completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /livez:
    get:
      operationId: Livez_get
      summary: Liveness probe
      description: Always returns 200 OK.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivezResponse'
  /readyz:
    get:
      operationId: Readyz_get
      summary: Readiness probe
      description: Returns 200 if the service is ready. Returns 503 otherwise.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyzResponse'
        '503':
          description: Service unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadyzResponse'
  /scrape:
    post:
      operationId: Scrape_create
      summary: Trigger scraper
      description: Starts a background Google Places scraper job.
      parameters: []
      responses:
        '202':
          description: The request has been accepted for processing, but processing has not yet completed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    LivezResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
    MessageResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ReadyzResponse:
      type: object
      required:
        - status
        - db
      properties:
        status:
          type: string
        db:
          type: string
servers:
  - url: http://localhost:8081
    description: Local development server
    variables: {}
