with-expecter: true
dir: "internal/mocks"
outpkg: "mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/neofyis/geopulse/internal/store:
    interfaces:
      Store:
  github.com/neofyis/geopulse/internal/app:
    interfaces:
      Service:
      Pinger:
