// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ListPlacesForExport(ctx context.Context) ([]ListPlacesForExportRow, error)
	ListPlacesNeedingEnrichment(ctx context.Context) ([]ListPlacesNeedingEnrichmentRow, error)
	UpdatePlaceEnrichment(ctx context.Context, arg UpdatePlaceEnrichmentParams) error
	UpsertPlace(ctx context.Context, arg UpsertPlaceParams) (UpsertPlaceRow, error)
}

var _ Querier = (*Queries)(nil)
