// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	generated "github.com/neofyis/geopulse/bff/internal/generated"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreatePlace provides a mock function with given fields: ctx, req
func (_m *MockService) CreatePlace(ctx context.Context, req generated.CreatePlaceRequest) (*generated.Place, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreatePlaceRequest) (*generated.Place, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, generated.CreatePlaceRequest) *generated.Place); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, generated.CreatePlaceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePlace'
type MockService_CreatePlace_Call struct {
	*mock.Call
}

// CreatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - req generated.CreatePlaceRequest
func (_e *MockService_Expecter) CreatePlace(ctx interface{}, req interface{}) *MockService_CreatePlace_Call {
	return &MockService_CreatePlace_Call{Call: _e.mock.On("CreatePlace", ctx, req)}
}

func (_c *MockService_CreatePlace_Call) Run(run func(ctx context.Context, req generated.CreatePlaceRequest)) *MockService_CreatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(generated.CreatePlaceRequest))
	})
	return _c
}

func (_c *MockService_CreatePlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_CreatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreatePlace_Call) RunAndReturn(run func(context.Context, generated.CreatePlaceRequest) (*generated.Place, error)) *MockService_CreatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePlace provides a mock function with given fields: ctx, placeID
func (_m *MockService) DeletePlace(ctx context.Context, placeID string) error {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePlace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, placeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeletePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePlace'
type MockService_DeletePlace_Call struct {
	*mock.Call
}

// DeletePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockService_Expecter) DeletePlace(ctx interface{}, placeID interface{}) *MockService_DeletePlace_Call {
	return &MockService_DeletePlace_Call{Call: _e.mock.On("DeletePlace", ctx, placeID)}
}

func (_c *MockService_DeletePlace_Call) Run(run func(ctx context.Context, placeID string)) *MockService_DeletePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeletePlace_Call) Return(_a0 error) *MockService_DeletePlace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeletePlace_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeletePlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatmap provides a mock function with given fields: ctx, minLat, minLng, maxLat, maxLng, cellSize, category
func (_m *MockService) GetHeatmap(ctx context.Context, minLat float64, minLng float64, maxLat float64, maxLng float64, cellSize float64, category string) ([]generated.HeatmapTile, error) {
	ret := _m.Called(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatmap")
	}

	var r0 []generated.HeatmapTile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, float64, string) ([]generated.HeatmapTile, error)); ok {
		return rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, float64, string) []generated.HeatmapTile); ok {
		r0 = rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]generated.HeatmapTile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, float64, float64, string) error); ok {
		r1 = rf(ctx, minLat, minLng, maxLat, maxLng, cellSize, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetHeatmap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatmap'
type MockService_GetHeatmap_Call struct {
	*mock.Call
}

// GetHeatmap is a helper method to define mock.On call
//   - ctx context.Context
//   - minLat float64
//   - minLng float64
//   - maxLat float64
//   - maxLng float64
//   - cellSize float64
//   - category string
func (_e *MockService_Expecter) GetHeatmap(ctx interface{}, minLat interface{}, minLng interface{}, maxLat interface{}, maxLng interface{}, cellSize interface{}, category interface{}) *MockService_GetHeatmap_Call {
	return &MockService_GetHeatmap_Call{Call: _e.mock.On("GetHeatmap", ctx, minLat, minLng, maxLat, maxLng, cellSize, category)}
}

func (_c *MockService_GetHeatmap_Call) Run(run func(ctx context.Context, minLat float64, minLng float64, maxLat float64, maxLng float64, cellSize float64, category string)) *MockService_GetHeatmap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(float64), args[5].(float64), args[6].(string))
	})
	return _c
}

func (_c *MockService_GetHeatmap_Call) Return(_a0 []generated.HeatmapTile, _a1 error) *MockService_GetHeatmap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetHeatmap_Call) RunAndReturn(run func(context.Context, float64, float64, float64, float64, float64, string) ([]generated.HeatmapTile, error)) *MockService_GetHeatmap_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroShapes provides a mock function with given fields: ctx
func (_m *MockService) GetMetroShapes(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroShapes")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetroShapes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroShapes'
type MockService_GetMetroShapes_Call struct {
	*mock.Call
}

// GetMetroShapes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMetroShapes(ctx interface{}) *MockService_GetMetroShapes_Call {
	return &MockService_GetMetroShapes_Call{Call: _e.mock.On("GetMetroShapes", ctx)}
}

func (_c *MockService_GetMetroShapes_Call) Run(run func(ctx context.Context)) *MockService_GetMetroShapes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMetroShapes_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetMetroShapes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetroShapes_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetMetroShapes_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetroStops provides a mock function with given fields: ctx
func (_m *MockService) GetMetroStops(ctx context.Context) (*generated.GeoJSONFeatureCollection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetroStops")
	}

	var r0 *generated.GeoJSONFeatureCollection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*generated.GeoJSONFeatureCollection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *generated.GeoJSONFeatureCollection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.GeoJSONFeatureCollection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetroStops_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetroStops'
type MockService_GetMetroStops_Call struct {
	*mock.Call
}

// GetMetroStops is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMetroStops(ctx interface{}) *MockService_GetMetroStops_Call {
	return &MockService_GetMetroStops_Call{Call: _e.mock.On("GetMetroStops", ctx)}
}

func (_c *MockService_GetMetroStops_Call) Run(run func(ctx context.Context)) *MockService_GetMetroStops_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMetroStops_Call) Return(_a0 *generated.GeoJSONFeatureCollection, _a1 error) *MockService_GetMetroStops_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetroStops_Call) RunAndReturn(run func(context.Context) (*generated.GeoJSONFeatureCollection, error)) *MockService_GetMetroStops_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlace provides a mock function with given fields: ctx, placeID
func (_m *MockService) GetPlace(ctx context.Context, placeID string) (*generated.Place, error) {
	ret := _m.Called(ctx, placeID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*generated.Place, error)); ok {
		return rf(ctx, placeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *generated.Place); ok {
		r0 = rf(ctx, placeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, placeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlace'
type MockService_GetPlace_Call struct {
	*mock.Call
}

// GetPlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
func (_e *MockService_Expecter) GetPlace(ctx interface{}, placeID interface{}) *MockService_GetPlace_Call {
	return &MockService_GetPlace_Call{Call: _e.mock.On("GetPlace", ctx, placeID)}
}

func (_c *MockService_GetPlace_Call) Run(run func(ctx context.Context, placeID string)) *MockService_GetPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetPlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_GetPlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetPlace_Call) RunAndReturn(run func(context.Context, string) (*generated.Place, error)) *MockService_GetPlace_Call {
	_c.Call.Return(run)
	return _c
}

// GetSaturation provides a mock function with given fields: ctx, lat, lng, radius, category
func (_m *MockService) GetSaturation(ctx context.Context, lat float64, lng float64, radius float64, category string) (*generated.SaturationResult, error) {
	ret := _m.Called(ctx, lat, lng, radius, category)

	if len(ret) == 0 {
		panic("no return value specified for GetSaturation")
	}

	var r0 *generated.SaturationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, string) (*generated.SaturationResult, error)); ok {
		return rf(ctx, lat, lng, radius, category)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, string) *generated.SaturationResult); ok {
		r0 = rf(ctx, lat, lng, radius, category)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.SaturationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, string) error); ok {
		r1 = rf(ctx, lat, lng, radius, category)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetSaturation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSaturation'
type MockService_GetSaturation_Call struct {
	*mock.Call
}

// GetSaturation is a helper method to define mock.On call
//   - ctx context.Context
//   - lat float64
//   - lng float64
//   - radius float64
//   - category string
func (_e *MockService_Expecter) GetSaturation(ctx interface{}, lat interface{}, lng interface{}, radius interface{}, category interface{}) *MockService_GetSaturation_Call {
	return &MockService_GetSaturation_Call{Call: _e.mock.On("GetSaturation", ctx, lat, lng, radius, category)}
}

func (_c *MockService_GetSaturation_Call) Run(run func(ctx context.Context, lat float64, lng float64, radius float64, category string)) *MockService_GetSaturation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(string))
	})
	return _c
}

func (_c *MockService_GetSaturation_Call) Return(_a0 *generated.SaturationResult, _a1 error) *MockService_GetSaturation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetSaturation_Call) RunAndReturn(run func(context.Context, float64, float64, float64, string) (*generated.SaturationResult, error)) *MockService_GetSaturation_Call {
	_c.Call.Return(run)
	return _c
}

// ListPlaces provides a mock function with given fields: ctx, category, tag
func (_m *MockService) ListPlaces(ctx context.Context, category string, tag string) ([]generated.Place, error) {
	ret := _m.Called(ctx, category, tag)

	if len(ret) == 0 {
		panic("no return value specified for ListPlaces")
	}

	var r0 []generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]generated.Place, error)); ok {
		return rf(ctx, category, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []generated.Place); ok {
		r0 = rf(ctx, category, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, category, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListPlaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPlaces'
type MockService_ListPlaces_Call struct {
	*mock.Call
}

// ListPlaces is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
//   - tag string
func (_e *MockService_Expecter) ListPlaces(ctx interface{}, category interface{}, tag interface{}) *MockService_ListPlaces_Call {
	return &MockService_ListPlaces_Call{Call: _e.mock.On("ListPlaces", ctx, category, tag)}
}

func (_c *MockService_ListPlaces_Call) Run(run func(ctx context.Context, category string, tag string)) *MockService_ListPlaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_ListPlaces_Call) Return(_a0 []generated.Place, _a1 error) *MockService_ListPlaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListPlaces_Call) RunAndReturn(run func(context.Context, string, string) ([]generated.Place, error)) *MockService_ListPlaces_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with given fields: ctx
func (_m *MockService) Ready(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Ready(ctx interface{}) *MockService_Ready_Call {
	return &MockService_Ready_Call{Call: _e.mock.On("Ready", ctx)}
}

func (_c *MockService_Ready_Call) Run(run func(ctx context.Context)) *MockService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_Ready_Call) Return(_a0 error) *MockService_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Ready_Call) RunAndReturn(run func(context.Context) error) *MockService_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlace provides a mock function with given fields: ctx, placeID, req
func (_m *MockService) UpdatePlace(ctx context.Context, placeID string, req generated.UpdatePlaceRequest) (*generated.Place, error) {
	ret := _m.Called(ctx, placeID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePlace")
	}

	var r0 *generated.Place
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdatePlaceRequest) (*generated.Place, error)); ok {
		return rf(ctx, placeID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, generated.UpdatePlaceRequest) *generated.Place); ok {
		r0 = rf(ctx, placeID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*generated.Place)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, generated.UpdatePlaceRequest) error); ok {
		r1 = rf(ctx, placeID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdatePlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlace'
type MockService_UpdatePlace_Call struct {
	*mock.Call
}

// UpdatePlace is a helper method to define mock.On call
//   - ctx context.Context
//   - placeID string
//   - req generated.UpdatePlaceRequest
func (_e *MockService_Expecter) UpdatePlace(ctx interface{}, placeID interface{}, req interface{}) *MockService_UpdatePlace_Call {
	return &MockService_UpdatePlace_Call{Call: _e.mock.On("UpdatePlace", ctx, placeID, req)}
}

func (_c *MockService_UpdatePlace_Call) Run(run func(ctx context.Context, placeID string, req generated.UpdatePlaceRequest)) *MockService_UpdatePlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(generated.UpdatePlaceRequest))
	})
	return _c
}

func (_c *MockService_UpdatePlace_Call) Return(_a0 *generated.Place, _a1 error) *MockService_UpdatePlace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdatePlace_Call) RunAndReturn(run func(context.Context, string, generated.UpdatePlaceRequest) (*generated.Place, error)) *MockService_UpdatePlace_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
