// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GtfsStop struct {
	StopID   string
	StopCode pgtype.Text
	StopName pgtype.Text
	StopDesc pgtype.Text
	StopLat  pgtype.Float8
	StopLon  pgtype.Float8
	Geom     interface{}
}

type OpportunityHeatmap struct {
	Geom     interface{}
	Category pgtype.Text
	Score    interface{}
}

type Place struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Location                 interface{}
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
}
