// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error)
	DeletePlace(ctx context.Context, placeID string) error
	GetMetroStops(ctx context.Context) ([]GetMetroStopsRow, error)
	GetPlace(ctx context.Context, placeID string) (GetPlaceRow, error)
	ListPlaces(ctx context.Context) ([]ListPlacesRow, error)
	ListPlacesByCategory(ctx context.Context, category pgtype.Text) ([]ListPlacesByCategoryRow, error)
	ListPlacesByCategoryAndTag(ctx context.Context, arg ListPlacesByCategoryAndTagParams) ([]ListPlacesByCategoryAndTagRow, error)
	ListPlacesByTag(ctx context.Context, dollar_1 string) ([]ListPlacesByTagRow, error)
	ListPlacesNeedingEnrichment(ctx context.Context) ([]ListPlacesNeedingEnrichmentRow, error)
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error)
	UpdatePlaceEnrichment(ctx context.Context, arg UpdatePlaceEnrichmentParams) error
	// Saturation and heatmap queries are executed as raw pgx queries in analytics.go
	// due to complex PostGIS CTE expressions that sqlc cannot type-check.
	UpsertPlace(ctx context.Context, arg UpsertPlaceParams) (UpsertPlaceRow, error)
}

var _ Querier = (*Queries)(nil)
