// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places (place_id, name, address, lat, lng, rating, business_status, category, location)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, ST_SetSRID(ST_MakePoint($5, $4), 4326))
RETURNING place_id, name, address, lat, lng, rating, business_status, category,
          website, formatted_phone_number, international_phone_number,
          opening_hours, reviews, editorial_summary, photos, types,
          price_level, user_ratings_total, utc_offset_minutes,
          google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
          reservable, takeout, wheelchair_accessible, tags, scraped_at
`

type CreatePlaceParams struct {
	PlaceID        string
	Name           string
	Address        pgtype.Text
	Lat            pgtype.Float8
	Lng            pgtype.Float8
	Rating         pgtype.Float8
	BusinessStatus pgtype.Text
	Category       pgtype.Text
}

type CreatePlaceRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Category                 pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
}

func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error) {
	row := q.db.QueryRow(ctx, createPlace,
		arg.PlaceID,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Rating,
		arg.BusinessStatus,
		arg.Category,
	)
	var i CreatePlaceRow
	err := row.Scan(
		&i.PlaceID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Rating,
		&i.BusinessStatus,
		&i.Category,
		&i.Website,
		&i.FormattedPhoneNumber,
		&i.InternationalPhoneNumber,
		&i.OpeningHours,
		&i.Reviews,
		&i.EditorialSummary,
		&i.Photos,
		&i.Types,
		&i.PriceLevel,
		&i.UserRatingsTotal,
		&i.UtcOffsetMinutes,
		&i.GoogleMapsUrl,
		&i.IconUrl,
		&i.CurbsidePickup,
		&i.Delivery,
		&i.DineIn,
		&i.Reservable,
		&i.Takeout,
		&i.WheelchairAccessible,
		&i.Tags,
		&i.ScrapedAt,
	)
	return i, err
}

const deletePlace = `-- name: DeletePlace :exec
DELETE FROM places WHERE place_id = $1
`

func (q *Queries) DeletePlace(ctx context.Context, placeID string) error {
	_, err := q.db.Exec(ctx, deletePlace, placeID)
	return err
}

const getMetroStops = `-- name: GetMetroStops :many
SELECT stop_id, stop_name, ST_Y(geom) AS stop_lat, ST_X(geom) AS stop_lon
FROM gtfs_stops
WHERE geom IS NOT NULL
ORDER BY stop_name
`

type GetMetroStopsRow struct {
	StopID   string
	StopName pgtype.Text
	StopLat  pgtype.Float8
	StopLon  pgtype.Float8
}

func (q *Queries) GetMetroStops(ctx context.Context) ([]GetMetroStopsRow, error) {
	rows, err := q.db.Query(ctx, getMetroStops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMetroStopsRow
	for rows.Next() {
		var i GetMetroStopsRow
		if err := rows.Scan(
			&i.StopID,
			&i.StopName,
			&i.StopLat,
			&i.StopLon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlace = `-- name: GetPlace :one
SELECT place_id, name, address, lat, lng, rating, business_status,
       website, formatted_phone_number, international_phone_number,
       opening_hours, reviews, editorial_summary, photos, types,
       price_level, user_ratings_total, utc_offset_minutes,
       google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
       reservable, takeout, wheelchair_accessible, category, tags, scraped_at,
       estimated_monthly_visitors, visitor_location_score
FROM places
WHERE place_id = $1
`

type GetPlaceRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
	EstimatedMonthlyVisitors pgtype.Int4
	VisitorLocationScore     pgtype.Numeric
}

func (q *Queries) GetPlace(ctx context.Context, placeID string) (GetPlaceRow, error) {
	row := q.db.QueryRow(ctx, getPlace, placeID)
	var i GetPlaceRow
	err := row.Scan(
		&i.PlaceID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Rating,
		&i.BusinessStatus,
		&i.Website,
		&i.FormattedPhoneNumber,
		&i.InternationalPhoneNumber,
		&i.OpeningHours,
		&i.Reviews,
		&i.EditorialSummary,
		&i.Photos,
		&i.Types,
		&i.PriceLevel,
		&i.UserRatingsTotal,
		&i.UtcOffsetMinutes,
		&i.GoogleMapsUrl,
		&i.IconUrl,
		&i.CurbsidePickup,
		&i.Delivery,
		&i.DineIn,
		&i.Reservable,
		&i.Takeout,
		&i.WheelchairAccessible,
		&i.Category,
		&i.Tags,
		&i.ScrapedAt,
		&i.EstimatedMonthlyVisitors,
		&i.VisitorLocationScore,
	)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many
SELECT place_id, name, address, lat, lng, rating, business_status,
       website, formatted_phone_number, international_phone_number,
       opening_hours, reviews, editorial_summary, photos, types,
       price_level, user_ratings_total, utc_offset_minutes,
       google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
       reservable, takeout, wheelchair_accessible, category, tags, scraped_at,
       estimated_monthly_visitors, visitor_location_score
FROM places
ORDER BY name
`

type ListPlacesRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
	EstimatedMonthlyVisitors pgtype.Int4
	VisitorLocationScore     pgtype.Numeric
}

func (q *Queries) ListPlaces(ctx context.Context) ([]ListPlacesRow, error) {
	rows, err := q.db.Query(ctx, listPlaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesRow
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Rating,
			&i.BusinessStatus,
			&i.Website,
			&i.FormattedPhoneNumber,
			&i.InternationalPhoneNumber,
			&i.OpeningHours,
			&i.Reviews,
			&i.EditorialSummary,
			&i.Photos,
			&i.Types,
			&i.PriceLevel,
			&i.UserRatingsTotal,
			&i.UtcOffsetMinutes,
			&i.GoogleMapsUrl,
			&i.IconUrl,
			&i.CurbsidePickup,
			&i.Delivery,
			&i.DineIn,
			&i.Reservable,
			&i.Takeout,
			&i.WheelchairAccessible,
			&i.Category,
			&i.Tags,
			&i.ScrapedAt,
			&i.EstimatedMonthlyVisitors,
			&i.VisitorLocationScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByCategory = `-- name: ListPlacesByCategory :many
SELECT place_id, name, address, lat, lng, rating, business_status,
       website, formatted_phone_number, international_phone_number,
       opening_hours, reviews, editorial_summary, photos, types,
       price_level, user_ratings_total, utc_offset_minutes,
       google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
       reservable, takeout, wheelchair_accessible, category, tags, scraped_at,
       estimated_monthly_visitors, visitor_location_score
FROM places
WHERE category = $1
ORDER BY name
`

type ListPlacesByCategoryRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
	EstimatedMonthlyVisitors pgtype.Int4
	VisitorLocationScore     pgtype.Numeric
}

func (q *Queries) ListPlacesByCategory(ctx context.Context, category pgtype.Text) ([]ListPlacesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesByCategoryRow
	for rows.Next() {
		var i ListPlacesByCategoryRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Rating,
			&i.BusinessStatus,
			&i.Website,
			&i.FormattedPhoneNumber,
			&i.InternationalPhoneNumber,
			&i.OpeningHours,
			&i.Reviews,
			&i.EditorialSummary,
			&i.Photos,
			&i.Types,
			&i.PriceLevel,
			&i.UserRatingsTotal,
			&i.UtcOffsetMinutes,
			&i.GoogleMapsUrl,
			&i.IconUrl,
			&i.CurbsidePickup,
			&i.Delivery,
			&i.DineIn,
			&i.Reservable,
			&i.Takeout,
			&i.WheelchairAccessible,
			&i.Category,
			&i.Tags,
			&i.ScrapedAt,
			&i.EstimatedMonthlyVisitors,
			&i.VisitorLocationScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByCategoryAndTag = `-- name: ListPlacesByCategoryAndTag :many
SELECT place_id, name, address, lat, lng, rating, business_status,
       website, formatted_phone_number, international_phone_number,
       opening_hours, reviews, editorial_summary, photos, types,
       price_level, user_ratings_total, utc_offset_minutes,
       google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
       reservable, takeout, wheelchair_accessible, category, tags, scraped_at,
       estimated_monthly_visitors, visitor_location_score
FROM places
WHERE category = $1
  AND (',' || tags || ',') LIKE ('%,' || $2::text || ',%')
ORDER BY name
`

type ListPlacesByCategoryAndTagParams struct {
	Category pgtype.Text
	Column2  string
}

type ListPlacesByCategoryAndTagRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
	EstimatedMonthlyVisitors pgtype.Int4
	VisitorLocationScore     pgtype.Numeric
}

func (q *Queries) ListPlacesByCategoryAndTag(ctx context.Context, arg ListPlacesByCategoryAndTagParams) ([]ListPlacesByCategoryAndTagRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByCategoryAndTag, arg.Category, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesByCategoryAndTagRow
	for rows.Next() {
		var i ListPlacesByCategoryAndTagRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Rating,
			&i.BusinessStatus,
			&i.Website,
			&i.FormattedPhoneNumber,
			&i.InternationalPhoneNumber,
			&i.OpeningHours,
			&i.Reviews,
			&i.EditorialSummary,
			&i.Photos,
			&i.Types,
			&i.PriceLevel,
			&i.UserRatingsTotal,
			&i.UtcOffsetMinutes,
			&i.GoogleMapsUrl,
			&i.IconUrl,
			&i.CurbsidePickup,
			&i.Delivery,
			&i.DineIn,
			&i.Reservable,
			&i.Takeout,
			&i.WheelchairAccessible,
			&i.Category,
			&i.Tags,
			&i.ScrapedAt,
			&i.EstimatedMonthlyVisitors,
			&i.VisitorLocationScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByTag = `-- name: ListPlacesByTag :many
SELECT place_id, name, address, lat, lng, rating, business_status,
       website, formatted_phone_number, international_phone_number,
       opening_hours, reviews, editorial_summary, photos, types,
       price_level, user_ratings_total, utc_offset_minutes,
       google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
       reservable, takeout, wheelchair_accessible, category, tags, scraped_at,
       estimated_monthly_visitors, visitor_location_score
FROM places
WHERE (',' || tags || ',') LIKE ('%,' || $1::text || ',%')
ORDER BY name
`

type ListPlacesByTagRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Category                 pgtype.Text
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
	EstimatedMonthlyVisitors pgtype.Int4
	VisitorLocationScore     pgtype.Numeric
}

func (q *Queries) ListPlacesByTag(ctx context.Context, dollar_1 string) ([]ListPlacesByTagRow, error) {
	rows, err := q.db.Query(ctx, listPlacesByTag, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesByTagRow
	for rows.Next() {
		var i ListPlacesByTagRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Rating,
			&i.BusinessStatus,
			&i.Website,
			&i.FormattedPhoneNumber,
			&i.InternationalPhoneNumber,
			&i.OpeningHours,
			&i.Reviews,
			&i.EditorialSummary,
			&i.Photos,
			&i.Types,
			&i.PriceLevel,
			&i.UserRatingsTotal,
			&i.UtcOffsetMinutes,
			&i.GoogleMapsUrl,
			&i.IconUrl,
			&i.CurbsidePickup,
			&i.Delivery,
			&i.DineIn,
			&i.Reservable,
			&i.Takeout,
			&i.WheelchairAccessible,
			&i.Category,
			&i.Tags,
			&i.ScrapedAt,
			&i.EstimatedMonthlyVisitors,
			&i.VisitorLocationScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesNeedingEnrichment = `-- name: ListPlacesNeedingEnrichment :many
SELECT place_id, name, lat, lng
FROM places
WHERE website IS NULL
   OR formatted_phone_number IS NULL
ORDER BY scraped_at ASC NULLS FIRST
LIMIT 100
`

type ListPlacesNeedingEnrichmentRow struct {
	PlaceID string
	Name    string
	Lat     pgtype.Float8
	Lng     pgtype.Float8
}

func (q *Queries) ListPlacesNeedingEnrichment(ctx context.Context) ([]ListPlacesNeedingEnrichmentRow, error) {
	rows, err := q.db.Query(ctx, listPlacesNeedingEnrichment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesNeedingEnrichmentRow
	for rows.Next() {
		var i ListPlacesNeedingEnrichmentRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Name,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places
SET name            = $1,
    address         = $2,
    lat             = $3,
    lng             = $4,
    rating          = $5,
    business_status = $6,
    category        = $7,
    location        = ST_SetSRID(ST_MakePoint($4, $3), 4326)
WHERE place_id = $8
RETURNING place_id, name, address, lat, lng, rating, business_status, category,
          website, formatted_phone_number, international_phone_number,
          opening_hours, reviews, editorial_summary, photos, types,
          price_level, user_ratings_total, utc_offset_minutes,
          google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
          reservable, takeout, wheelchair_accessible, tags, scraped_at
`

type UpdatePlaceParams struct {
	Name           string
	Address        pgtype.Text
	Lat            pgtype.Float8
	Lng            pgtype.Float8
	Rating         pgtype.Float8
	BusinessStatus pgtype.Text
	Category       pgtype.Text
	PlaceID        string
}

type UpdatePlaceRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Category                 pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
}

func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (UpdatePlaceRow, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Rating,
		arg.BusinessStatus,
		arg.Category,
		arg.PlaceID,
	)
	var i UpdatePlaceRow
	err := row.Scan(
		&i.PlaceID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Rating,
		&i.BusinessStatus,
		&i.Category,
		&i.Website,
		&i.FormattedPhoneNumber,
		&i.InternationalPhoneNumber,
		&i.OpeningHours,
		&i.Reviews,
		&i.EditorialSummary,
		&i.Photos,
		&i.Types,
		&i.PriceLevel,
		&i.UserRatingsTotal,
		&i.UtcOffsetMinutes,
		&i.GoogleMapsUrl,
		&i.IconUrl,
		&i.CurbsidePickup,
		&i.Delivery,
		&i.DineIn,
		&i.Reservable,
		&i.Takeout,
		&i.WheelchairAccessible,
		&i.Tags,
		&i.ScrapedAt,
	)
	return i, err
}

const updatePlaceEnrichment = `-- name: UpdatePlaceEnrichment :exec
UPDATE places
SET website                    = $2,
    formatted_phone_number     = $3,
    international_phone_number = $4,
    opening_hours              = $5,
    reviews                    = $6,
    editorial_summary          = $7,
    photos                     = $8,
    types                      = $9,
    price_level                = $10,
    user_ratings_total         = $11,
    utc_offset_minutes         = $12,
    google_maps_url            = $13,
    icon_url                   = $14,
    curbside_pickup            = $15,
    delivery                   = $16,
    dine_in                    = $17,
    reservable                 = $18,
    takeout                    = $19,
    wheelchair_accessible      = $20
WHERE place_id = $1
`

type UpdatePlaceEnrichmentParams struct {
	PlaceID                  string
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
}

func (q *Queries) UpdatePlaceEnrichment(ctx context.Context, arg UpdatePlaceEnrichmentParams) error {
	_, err := q.db.Exec(ctx, updatePlaceEnrichment,
		arg.PlaceID,
		arg.Website,
		arg.FormattedPhoneNumber,
		arg.InternationalPhoneNumber,
		arg.OpeningHours,
		arg.Reviews,
		arg.EditorialSummary,
		arg.Photos,
		arg.Types,
		arg.PriceLevel,
		arg.UserRatingsTotal,
		arg.UtcOffsetMinutes,
		arg.GoogleMapsUrl,
		arg.IconUrl,
		arg.CurbsidePickup,
		arg.Delivery,
		arg.DineIn,
		arg.Reservable,
		arg.Takeout,
		arg.WheelchairAccessible,
	)
	return err
}

const upsertPlace = `-- name: UpsertPlace :one

INSERT INTO places (
    place_id, name, address, lat, lng, rating, business_status, category,
    website, formatted_phone_number, international_phone_number,
    opening_hours, reviews, editorial_summary, photos, types,
    price_level, user_ratings_total, utc_offset_minutes,
    google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
    reservable, takeout, wheelchair_accessible, tags, scraped_at,
    location
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22, $23, $24,
    $25, $26, $27, $28, $29,
    ST_SetSRID(ST_MakePoint($5, $4), 4326)
)
ON CONFLICT (place_id) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    rating = EXCLUDED.rating,
    business_status = EXCLUDED.business_status,
    category = EXCLUDED.category,
    website = EXCLUDED.website,
    formatted_phone_number = EXCLUDED.formatted_phone_number,
    international_phone_number = EXCLUDED.international_phone_number,
    opening_hours = EXCLUDED.opening_hours,
    reviews = EXCLUDED.reviews,
    editorial_summary = EXCLUDED.editorial_summary,
    photos = EXCLUDED.photos,
    types = EXCLUDED.types,
    price_level = EXCLUDED.price_level,
    user_ratings_total = EXCLUDED.user_ratings_total,
    utc_offset_minutes = EXCLUDED.utc_offset_minutes,
    google_maps_url = EXCLUDED.google_maps_url,
    icon_url = EXCLUDED.icon_url,
    curbside_pickup = EXCLUDED.curbside_pickup,
    delivery = EXCLUDED.delivery,
    dine_in = EXCLUDED.dine_in,
    reservable = EXCLUDED.reservable,
    takeout = EXCLUDED.takeout,
    wheelchair_accessible = EXCLUDED.wheelchair_accessible,
    tags = EXCLUDED.tags,
    scraped_at = EXCLUDED.scraped_at,
    location = EXCLUDED.location
RETURNING place_id, name, address, lat, lng, rating, business_status, category,
          website, formatted_phone_number, international_phone_number,
          opening_hours, reviews, editorial_summary, photos, types,
          price_level, user_ratings_total, utc_offset_minutes,
          google_maps_url, icon_url, curbside_pickup, delivery, dine_in,
          reservable, takeout, wheelchair_accessible, tags, scraped_at
`

type UpsertPlaceParams struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Category                 pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
}

type UpsertPlaceRow struct {
	PlaceID                  string
	Name                     string
	Address                  pgtype.Text
	Lat                      pgtype.Float8
	Lng                      pgtype.Float8
	Rating                   pgtype.Float8
	BusinessStatus           pgtype.Text
	Category                 pgtype.Text
	Website                  pgtype.Text
	FormattedPhoneNumber     pgtype.Text
	InternationalPhoneNumber pgtype.Text
	OpeningHours             pgtype.Text
	Reviews                  pgtype.Text
	EditorialSummary         pgtype.Text
	Photos                   pgtype.Text
	Types                    pgtype.Text
	PriceLevel               pgtype.Int4
	UserRatingsTotal         pgtype.Int4
	UtcOffsetMinutes         pgtype.Int4
	GoogleMapsUrl            pgtype.Text
	IconUrl                  pgtype.Text
	CurbsidePickup           pgtype.Bool
	Delivery                 pgtype.Bool
	DineIn                   pgtype.Bool
	Reservable               pgtype.Bool
	Takeout                  pgtype.Bool
	WheelchairAccessible     pgtype.Bool
	Tags                     pgtype.Text
	ScrapedAt                pgtype.Timestamptz
}

// Saturation and heatmap queries are executed as raw pgx queries in analytics.go
// due to complex PostGIS CTE expressions that sqlc cannot type-check.
func (q *Queries) UpsertPlace(ctx context.Context, arg UpsertPlaceParams) (UpsertPlaceRow, error) {
	row := q.db.QueryRow(ctx, upsertPlace,
		arg.PlaceID,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Rating,
		arg.BusinessStatus,
		arg.Category,
		arg.Website,
		arg.FormattedPhoneNumber,
		arg.InternationalPhoneNumber,
		arg.OpeningHours,
		arg.Reviews,
		arg.EditorialSummary,
		arg.Photos,
		arg.Types,
		arg.PriceLevel,
		arg.UserRatingsTotal,
		arg.UtcOffsetMinutes,
		arg.GoogleMapsUrl,
		arg.IconUrl,
		arg.CurbsidePickup,
		arg.Delivery,
		arg.DineIn,
		arg.Reservable,
		arg.Takeout,
		arg.WheelchairAccessible,
		arg.Tags,
		arg.ScrapedAt,
	)
	var i UpsertPlaceRow
	err := row.Scan(
		&i.PlaceID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Rating,
		&i.BusinessStatus,
		&i.Category,
		&i.Website,
		&i.FormattedPhoneNumber,
		&i.InternationalPhoneNumber,
		&i.OpeningHours,
		&i.Reviews,
		&i.EditorialSummary,
		&i.Photos,
		&i.Types,
		&i.PriceLevel,
		&i.UserRatingsTotal,
		&i.UtcOffsetMinutes,
		&i.GoogleMapsUrl,
		&i.IconUrl,
		&i.CurbsidePickup,
		&i.Delivery,
		&i.DineIn,
		&i.Reservable,
		&i.Takeout,
		&i.WheelchairAccessible,
		&i.Tags,
		&i.ScrapedAt,
	)
	return i, err
}
